"""LangChain Agent - single-call with tools or structured output (no ReAct)
Version: single-call v2 - pre-fragmented / regex fragmentation only (no Fast fragmentation, no second LLM).
"""
import httpx
from langchain_openai import ChatOpenAI
from tools.dynamic_function_call_tool import DynamicFunctionCallTool
from services.agent_config_service import AgentConfigService
from services.function_call_processor import FunctionCallProcessor
from langchain_community.callbacks.manager import get_openai_callback
from callbacks.token_usage_callback import TokenUsageCallback
from config.settings import settings
from utils.logger import logger
from utils.brasilia_time import get_brasilia_placeholders
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage

# Timeout para chamadas OpenAI (1 chamada por mensagem)
OPENAI_HTTP_TIMEOUT = httpx.Timeout(connect=15.0, read=90.0, write=30.0, pool=30.0)

def _should_fallback_model(exc: Exception) -> bool:
    name = exc.__class__.__name__
    msg = str(exc) or ""
    if name == "NotFoundError":
        return True
    if "model_not_found" in msg or "does not exist or you do not have access" in msg:
        return True
    return False

def _is_temperature_unsupported_error(exc: Exception) -> bool:
    """
    Detecta erro de temperatura não suportada (alguns modelos nano só aceitam temperatura padrão = 1.0).
    """
    name = exc.__class__.__name__
    msg = str(exc) or ""
    if name == "BadRequestError":
        if "temperature" in msg.lower() and ("does not support" in msg.lower() or "only the default" in msg.lower()):
            return True
    if "unsupported_value" in msg.lower() and "temperature" in msg.lower():
        return True
    return False

def _fallback_model(model: str | None) -> str | None:
    if not model:
        return model
    model_clean = model.strip()
    if model_clean == "gpt-4o-nano":
        return "gpt-4o-mini"
    if model_clean == "gpt-5-nano":
        return "gpt-4o-mini"  # Fallback para gpt-4o-mini também
    return model


class FragmentedResponse(BaseModel):
    """
    Structured output schema for fragmented responses
    Matches the JSON schema with strict mode enabled (additionalProperties: false)
    """
    response: str = Field(description="The response that would be generated by the assistant.")
    fragments: List[str] = Field(description="All segments of the response generated by the assistant, dividing all the information. Never split times (13:00), dates, or monetary values across fragments.")
    
    model_config = {
        # Ensure strict mode: no additional properties allowed
        "extra": "forbid",
        "json_schema_extra": {
            "name": "fragmented_response",
            "strict": True
        }
    }


class AlteseAgent:
    """
    LangChain Agent for Altese customer service
    Uses ReAct pattern with custom tools
    """
    
    def __init__(self, memory_manager, routing_service, agent_config_service: AgentConfigService, function_call_processor: Optional[FunctionCallProcessor] = None, multi_agent_config_service=None):
        self.memory_manager = memory_manager
        self.routing_service = routing_service
        self.agent_config_service = agent_config_service
        self.function_call_processor = function_call_processor
        self.multi_agent_config_service = multi_agent_config_service
        
        # Model will be loaded from database in initialize_tools, fallback to env var
        self._model_from_db = None
        
        # Initialize LLM with optimized settings for speed
        # Model will be updated in initialize_tools if found in database
        self.llm = ChatOpenAI(
            model=settings.openai_model,
            temperature=0.7,
            streaming=False,  # Disable streaming for now
            api_key=settings.openai_api_key,
            timeout=OPENAI_HTTP_TIMEOUT,
            max_retries=0,
        )
        
        # Initialize LLM with structured output for fragmented responses
        # Strict mode is enforced via Pydantic model (Config.extra = "forbid")
        # This ensures no additional properties are allowed, matching the JSON schema
        self.structured_llm = self.llm.with_structured_output(
            FragmentedResponse,
            method="function_calling"  # Use function_calling method for structured output
        )
        
        # Tools serão criadas dinamicamente do banco de dados em initialize_tools()
        # Nenhuma tool hardcoded - tudo gerenciado via Super Admin
        self.tools: List[DynamicFunctionCallTool] = []
        self._tools_initialized = False
        
        self.agent = None
        self.agent_executor = None
    
    async def initialize_tools(self):
        """
        Initialize all tools by loading their descriptions dynamically
        This must be called before using the agent
        Filters tools to only include those that are active (isActive = true)
        """
        if self._tools_initialized:
            return
        
        # Load model and temperature from database (model optional, temperature default 0.7)
        model_to_use = settings.openai_model
        temp_to_use = 0.7
        try:
            model_from_db = await self.agent_config_service.get_openai_model()
            if model_from_db:
                self._model_from_db = model_from_db
                model_to_use = model_from_db
                logger.info(f"✅ Using OpenAI model from database: {model_from_db}")
            else:
                logger.info(f"Using OpenAI model from environment: {settings.openai_model}")
        except Exception as e:
            logger.warning(f"Error loading model from database, using env var: {e}")

        try:
            temp_to_use = await self.agent_config_service.get_agent_temperature()
            logger.info(f"✅ Using agent temperature from database: {temp_to_use}")
        except Exception as e:
            logger.warning(f"Error loading temperature from database, using default 0.7: {e}")

        # Always (re)create LLM with model + temperature from config
        self.llm = ChatOpenAI(
            model=model_to_use,
            temperature=temp_to_use,
            streaming=False,
            api_key=settings.openai_api_key,
            timeout=OPENAI_HTTP_TIMEOUT,
            max_retries=0,
        )
        self.structured_llm = self.llm.with_structured_output(
            FragmentedResponse,
            method="function_calling"
        )
        
        # CRIAR TOOLS DINAMICAMENTE DO BANCO DE DADOS
        # Não há mais tools hardcoded - tudo é gerenciado via Super Admin
        logger.info("🔄 Creating tools dynamically from database...")
        
        # Busca function calls ativas com seus metadados e prompts
        function_calls_data = await self.agent_config_service.get_active_function_calls_with_metadata()
        
        if not function_calls_data:
            logger.warning("⚠️  No active function calls found in database! Agent will have no tools available.")
            logger.warning("⚠️  Please create and activate function calls via Super Admin panel.")
            self.tools = []
        else:
            # Cria tools dinamicamente para cada function call ativa
            created_tools = []
            for fc_data in function_calls_data:
                try:
                    tool = DynamicFunctionCallTool(
                        function_call_name=fc_data['name'],
                        description=fc_data['prompt'],
                        input_schema=fc_data.get('input_schema'),
                        required_fields=fc_data.get('required_fields') or [],
                        optional_fields=fc_data.get('optional_fields') or [],
                        agent_config_service=self.agent_config_service
                    )
                    created_tools.append(tool)
                    logger.info(f"✅ Created dynamic tool: {fc_data['name']}")
                except Exception as e:
                    logger.error(f"❌ Failed to create tool for {fc_data['name']}: {e}", exc_info=True)
            
            self.tools = created_tools
            logger.info(f"✅ Created {len(self.tools)} dynamic tools from database")
        
        # Carrega descrições atualizadas para as tools (já foram carregadas, mas força reload se necessário)
        logger.info("Loading function call prompts for dynamic tools...")
        for tool in self.tools:
            if hasattr(tool, '_load_description'):
                try:
                    await tool._load_description()
                    logger.debug(f"Loaded prompt for tool: {tool.name}")
                except Exception as e:
                    logger.warning(f"Failed to load prompt for {tool.name}: {e}")
        
        # Single-call com tools: não usamos mais ReAct (múltiplas chamadas).
        # Sem tools: LLM direto com structured output. Com tools: 1 chamada com bind_tools.
        self.agent = None
        self.agent_executor = None
        if not self.tools:
            logger.warning("⚠️  NO TOOLS AVAILABLE - Agent will use LLM with structured output")
            logger.warning("⚠️  Please create and activate function calls via Super Admin panel")
        else:
            logger.info(f"✅ Single-call mode: {len(self.tools)} tools will be used via bind_tools (1 LLM call per message)")

        self._tools_initialized = True
        logger.info(f"✅ All {len(self.tools)} active tools initialized with dynamic prompts")
        logger.info("🔧 Agent mode: single-call v2 (pre-fragmented / regex only, no ReAct, no second LLM)")
        logger.info("LangChain Agent initialized (only active tools loaded)")

    def invalidate_tools(self) -> None:
        """
        Reset tools/LLM initialization so next request will re-run initialize_tools.
        Used when agent_temperature (or model) is updated via Super Admin.
        """
        self._tools_initialized = False
        self.agent = None
        self.agent_executor = None
        logger.info("🔄 Agent tools invalidated - next request will reload model/temperature from database")
    
    async def format_system_message(self, chat_history: str, context: str) -> str:
        """Format system message with context - loads prompt dynamically from database (legacy method)"""
        # Load agent prompt dynamically from database
        agent_prompt = await self.agent_config_service.get_agent_prompt()
        
        system_parts = [agent_prompt]
        
        if context:
            system_parts.append(f"\nCONTEXTO ADICIONAL:\n{context}")
        
        if chat_history:
            system_parts.append(f"\nHISTÓRICO DA CONVERSA:\n{chat_history}")
        
        return "\n".join(system_parts)
    
    async def format_system_message_new_structure(
        self,
        recent_messages: str,
        intermediate_summary: str,
        rag_context: str,
        last_attendance_summary: str = "",
        open_cases: list = None,
        attendance_id: str = "",
        triagem_context: dict = None,
        operational_state: str | None = None,
        attendance_context: str | None = None,
    ) -> str:
        """Format system message with new context structure (SOMENTE contexto do sistema).
        
        IMPORTANTE: Não incluir prompt do painel aqui. O prompt configurado e o prompt universal
        são concatenados externamente na montagem final do SYSTEM message, para termos separação
        determinística no execution_log.
        """
        system_parts = []
        
        # DATA E HORA ATUAL (Brasília) - SEMPRE presente para saudação e function calls (formato XML)
        try:
            ph = get_brasilia_placeholders()
            system_parts.append("")
            system_parts.append("<DataHoraAtual>")
            system_parts.append(f"  <Data>{ph.get('{{data_brasilia}}', 'N/A')}</Data>")
            system_parts.append(f"  <Horario>{ph.get('{{horario_brasilia}}', 'N/A')}</Horario>")
            system_parts.append(f"  <DiaSemana>{ph.get('{{dia_semana_brasilia}}', 'N/A')}</DiaSemana>")
            system_parts.append("  <Uso>Use para: saudação adequada (Bom dia / Boa tarde / Boa noite) e para function calls que dependam de data/hora.</Uso>")
            system_parts.append("</DataHoraAtual>")
        except Exception:
            pass  # não quebrar o fluxo se falhar
        
        # ESTRUTURA HIERÁRQUICA: ATENDIMENTO -> STATUS + MEMÓRIA
        # Iniciar estrutura XML do atendimento
        if attendance_id:
            system_parts.append("")
            system_parts.append("<Atendimento>")
            
            # STATUS DO ATENDIMENTO
            _state_labels = {
                "TRIAGEM": "em triagem (inicial)",
                "ABERTO": "aberto",
                "EM_ATENDIMENTO": "em atendimento (com vendedor)",
                "AGUARDANDO_CLIENTE": "aguardando resposta do cliente",
                "AGUARDANDO_VENDEDOR": "aguardando vendedor",
                "FECHADO_OPERACIONAL": "fechado",
            }
            _ctx_labels = {
                "novo": "Novo atendimento",
                "reaberto": "Atendimento reaberto (retomamos o anterior)",
                "em_andamento": "Conversa em andamento"
            }
            
            system_parts.append("  <Status>")
            if operational_state:
                label = _state_labels.get(operational_state, operational_state)
                system_parts.append(f"    <Estado>{label}</Estado>")
            else:
                system_parts.append("    <Estado>não especificado</Estado>")
            
            if attendance_context and attendance_context in _ctx_labels:
                system_parts.append(f"    <Contexto>{_ctx_labels[attendance_context]}</Contexto>")
            else:
                system_parts.append("    <Contexto>não especificado</Contexto>")
            
            system_parts.append("    <Instrucao>Use isso para decidir quando informar que retomamos o atendimento (reaberto), quando é novo ou em andamento. Não sugira 'abrir' atendimento se já estiver aberto ou em andamento.</Instrucao>")
            system_parts.append("  </Status>")
            
            # MEMÓRIA HIERÁRQUICA: RECENTES + RESUMO + RAG (dentro de Atendimento)
            system_parts.append("  <Memoria>")
            system_parts.append("    <Recentes tipo=\"curto-prazo\">")
            if recent_messages:
                system_parts.append("      <Conteudo>")
                for line in (recent_messages or "").strip().split("\n"):
                    system_parts.append("        " + line)
                system_parts.append("      </Conteudo>")
                system_parts.append("      <Descricao>Mensagens recentes da conversa atual (todas após a 10ª mensagem mais antiga do cliente)</Descricao>")
            else:
                system_parts.append("      <Conteudo>Primeiro contato do cliente.</Conteudo>")
                system_parts.append("      <Descricao>Nenhuma mensagem anterior no atendimento</Descricao>")
            system_parts.append("    </Recentes>")
            system_parts.append("    <Resumo tipo=\"medio-prazo\">")
            if intermediate_summary:
                system_parts.append("      <Conteudo>")
                for line in (intermediate_summary or "").strip().split("\n"):
                    system_parts.append("        " + line)
                system_parts.append("      </Conteudo>")
                system_parts.append("      <Descricao>Resumo das 30 mensagens do cliente antes da janela recente (gerado a cada 10 mensagens do cliente)</Descricao>")
            else:
                system_parts.append("      <Conteudo>Nenhum resumo disponível.</Conteudo>")
                system_parts.append("      <Descricao>Conversa ainda não possui histórico suficiente para resumo</Descricao>")
            system_parts.append("    </Resumo>")
            system_parts.append("    <RAG tipo=\"longo-prazo\">")
            if rag_context:
                system_parts.append("      <Conteudo>")
                for line in (rag_context or "").strip().split("\n"):
                    system_parts.append("        " + line)
                system_parts.append("      </Conteudo>")
                system_parts.append("      <Descricao>Contexto recuperado de até 100 atendimentos anteriores do cliente (acionado quando informação não está em Recentes nem em Resumo)</Descricao>")
            else:
                system_parts.append("      <Conteudo>Nenhum contexto histórico recuperado.</Conteudo>")
                system_parts.append("      <Descricao>Cliente não possui atendimentos anteriores relevantes ou informação já está em Recentes/Resumo</Descricao>")
            system_parts.append("    </RAG>")
            system_parts.append("    <Instrucao>Use SEMPRE o conteúdo de Recentes e Resumo acima. NUNCA pergunte novamente informações que o cliente já informou (nome, veículo, peça, problema, etc.); considere-as como já conhecidas e prossiga a partir delas.</Instrucao>")
            system_parts.append("  </Memoria>")
            if open_cases:
                system_parts.append("  <CasosAbertos>")
                for caso in open_cases:
                    type_label = caso.get('type_label', caso.get('type_key', ''))
                    title = caso.get('title') or 'Sem título'
                    status = caso.get('status', '')
                    system_parts.append(f"    <Caso tipo='{type_label}' status='{status}'>{title}</Caso>")
                system_parts.append("    <Descricao>Situações criadas por function calls que precisam de resposta humana (vendedor/supervisor)</Descricao>")
                system_parts.append("  </CasosAbertos>")
            system_parts.append("</Atendimento>")
        
        # Informações de triagem e contexto adicional (fora da estrutura do Atendimento)
        if triagem_context:
            triagem_info = []
            
            # Verificar se tem atendimentos anteriores
            if triagem_context.get('has_previous_attendances'):
                closed_count = len(triagem_context.get('closed_attendances', []))
                triagem_info.append(f"O cliente possui {closed_count} atendimento(s) anterior(es) fechado(s).")
            
            # Verificar atendimentos em aberto
            if triagem_context.get('has_open_attendances'):
                open_attendances = triagem_context.get('open_attendances', [])
                triagem_info.append(f"\n⚠️ ATENÇÃO: O cliente possui {len(open_attendances)} atendimento(s) em aberto:")
                for att in open_attendances:
                    state = att.get('operational_state', 'DESCONHECIDO')
                    cases = att.get('open_cases', [])
                    incomplete = att.get('incomplete_process', False)
                    
                    info_line = f"- Atendimento #{att.get('id', 'N/A')[:8]}... (Estado: {state})"
                    if cases:
                        case_types = [c.get('type_label', c.get('type_key', '')) for c in cases]
                        info_line += f" com {len(cases)} caso(s) aberto(s): {', '.join(case_types)}"
                    if incomplete:
                        info_line += " [PROCESSO INCOMPLETO - cliente parou no meio]"
                    triagem_info.append(info_line)
            
            # Verificar últimos 3 atendimentos com casos abertos
            recent_with_cases = triagem_context.get('recent_with_open_cases', [])
            if recent_with_cases:
                triagem_info.append(f"\n📋 Nos últimos 3 atendimentos, há casos em aberto:")
                for att in recent_with_cases:
                    cases = att.get('open_cases', [])
                    case_types = [c.get('type_label', c.get('type_key', '')) for c in cases]
                    triagem_info.append(f"- Atendimento #{att.get('id', 'N/A')[:8]}...: {', '.join(case_types)}")
            
            # Verificar se parou no meio de algum processo
            if triagem_context.get('last_3_has_incomplete'):
                triagem_info.append(f"\n⏸️ O cliente parou no meio de algum processo em atendimento(s) anterior(es).")
            
            if triagem_info:
                system_parts.append("\n### CONTEXTO DE TRIAGEM - HISTÓRICO DO CLIENTE")
                system_parts.append("\n".join(triagem_info))
                system_parts.append("\n⚠️ IMPORTANTE: Use essas informações para perguntar ao cliente se ele quer:")
                system_parts.append("- Reabrir um atendimento antigo")
                system_parts.append("- Continuar um atendimento que está em aberto")
                system_parts.append("- Ou iniciar um novo atendimento")
                system_parts.append("Só pode haver UM atendimento ativo por cliente. Se o cliente escolher continuar/reabrir, você deve usar a function call apropriada para isso.")
        
        # Resumo do último atendimento (quando atendimento atual é novo e cliente tinha atendimentos finalizados)
        if last_attendance_summary and last_attendance_summary.strip():
            system_parts.append(f"\n### Resumo do último atendimento do cliente\n{last_attendance_summary.strip()}")
        
        # IMPORTANTE: Instruções sobre tags de mensagem (SEMPRE presente em todos os agentes) - formato XML
        # Esta seção deve estar presente em 100% dos prompts - informação do sistema
        system_parts.append("")
        system_parts.append("<Importante>")
        system_parts.append("  <Instrucao>As tags &lt;Text&gt;, &lt;Audio&gt;, &lt;Image&gt; indicam o tipo original da mensagem que você recebeu. INTERPRETE o conteúdo como se você tivesse realmente ouvido o áudio (quando marcado como &lt;Audio&gt;) ou visto a imagem (quando marcado como &lt;Image&gt;). NÃO trate como uma transcrição ou descrição - responda como se tivesse experiência direta com o conteúdo original.</Instrucao>")
        system_parts.append("  <Instrucao>Você NÃO deve retornar essas tags na sua resposta. Responda normalmente ou acione a ferramenta indicada pelos gatilhos do prompt.</Instrucao>")
        system_parts.append("</Importante>")

        # DadosParaOrcamento: variáveis dinâmicas (Capturados, UltimoEnviado) da FC pedido-orcamento
        if attendance_id:
            dados_orcamento_xml = await self.memory_manager.get_dados_para_orcamento_xml(attendance_id)
            if dados_orcamento_xml:
                system_parts.append(dados_orcamento_xml)

        return "\n".join(system_parts).strip()
    
    async def _build_execution_log(
        self,
        context_parts: dict | None,
        messages_sent: list | None,
        intermediate_steps: list,
    ) -> dict:
        """Build execution_log for Custos → Ver Log da Execução.
        
        Args:
            context_parts: dict with keys:
                - configured_prompt: prompt configurado no painel
                - universal_prompt: prompt universal (se existir)
                - conversation_history: histórico de mensagens
                - system_additions: dict com {summary, rag, cases, triagem, status}
                - final_prompt: prompt final montado
                - message_content: mensagem atual do cliente
            messages_sent: lista de mensagens enviadas ao LLM
            intermediate_steps: passos intermediários (tools)
        """
        import json as _json
        out: Dict[str, Any] = {}
        
        # 1. Prompt configurado no painel
        if context_parts and context_parts.get("configured_prompt"):
            out["configuredPrompt"] = context_parts["configured_prompt"]
        
        # 2. Prompt universal (se existir)
        if context_parts and context_parts.get("universal_prompt"):
            out["universalPrompt"] = context_parts["universal_prompt"]
        
        # 3. Histórico da conversa (mensagens anteriores reais)
        if context_parts and context_parts.get("conversation_history"):
            out["conversationHistory"] = context_parts["conversation_history"]
        
        # 4. Contexto adicionado pelo sistema
        if context_parts and context_parts.get("system_additions"):
            out["systemAdditions"] = context_parts["system_additions"]

        # 4.1 Texto do contexto montado pelo sistema (separado, sem parsing)
        if context_parts and context_parts.get("system_context_text"):
            out["systemContextText"] = context_parts["system_context_text"]

        # 4.2 Instruções finais adicionadas pelo sistema - REMOVIDO DOS LOGS (já exibidas no sistema)
        # As instruções finais ainda são enviadas ao LLM, mas não aparecem nos logs
        
        # 5. Prompt final montado (tudo junto)
        if context_parts and context_parts.get("final_prompt"):
            out["finalPrompt"] = context_parts["final_prompt"]
        
        # 6. Payload OpenAI (formato exato enviado)
        model = getattr(self, "_model_from_db", None) or (settings.openai_model if settings else "gpt-4o-mini")
        temp = 0.7
        try:
            if self.agent_config_service:
                model_from_db = await self.agent_config_service.get_openai_model()
                if model_from_db:
                    model = model_from_db
                temp = await self.agent_config_service.get_agent_temperature()
        except Exception:
            pass
        if messages_sent:
            openai_messages = []
            for m in messages_sent:
                c = (m.content or "") if hasattr(m, "content") else ""
                role = "system" if isinstance(m, SystemMessage) else ("user" if isinstance(m, HumanMessage) else "assistant")
                openai_messages.append({"role": role, "content": c})
            # Capturar metadados do LLM
            llm_metadata = {}
            if hasattr(self.llm, "model_name"):
                llm_metadata["model"] = self.llm.model_name
            elif hasattr(self.llm, "model"):
                llm_metadata["model"] = self.llm.model
            else:
                llm_metadata["model"] = model
            if hasattr(self.llm, "temperature"):
                llm_metadata["temperature"] = self.llm.temperature
            else:
                llm_metadata["temperature"] = temp
            if hasattr(self.llm, "max_tokens"):
                llm_metadata["max_tokens"] = self.llm.max_tokens
            if hasattr(self.llm, "top_p"):
                llm_metadata["top_p"] = self.llm.top_p
            if hasattr(self.llm, "frequency_penalty"):
                llm_metadata["frequency_penalty"] = self.llm.frequency_penalty
            if hasattr(self.llm, "presence_penalty"):
                llm_metadata["presence_penalty"] = self.llm.presence_penalty
            out["openaiPayload"] = {
                **llm_metadata,
                "messages": openai_messages,
            }
        
        # Tools disponíveis
        tools_av = []
        for t in (self.tools or []):
            name = getattr(t, "name", None) or "?"
            desc = (getattr(t, "description", None) or "")[:500]
            schema = {}
            if hasattr(t, "args_schema") and t.args_schema is not None:
                try:
                    if hasattr(t.args_schema, "model_json_schema"):
                        schema = t.args_schema.model_json_schema()
                    elif hasattr(t.args_schema, "schema"):
                        schema = getattr(t.args_schema, "schema")() if callable(getattr(t.args_schema, "schema")) else {}
                    else:
                        schema = {}
                except Exception:
                    schema = {}
            tools_av.append({"name": name, "description": desc, "parameters": schema})
        out["toolsAvailable"] = tools_av
        out["specialist"] = {"name": "Agente Único"}
        
        # Tools utilizadas
        tools_used = []
        for step in (intermediate_steps or []):
            if not step or len(step) < 2:
                continue
            action, res = step[0], step[1]
            name = getattr(action, "tool", None) or (action.get("tool") if isinstance(action, dict) else "?")
            args = getattr(action, "tool_input", None) or (action.get("tool_input") if isinstance(action, dict) else {})
            if not isinstance(args, dict):
                args = {}
            result_str = str(res) if res is not None else ""
            try:
                args = _json.loads(_json.dumps(args, default=str))
            except Exception:
                pass
            tools_used.append({"name": name, "arguments": args, "result": result_str[:2000], "success": "error" not in result_str.lower()})
        out["toolsUsed"] = tools_used
        return out
    
    async def process_message(
        self,
        message_content: str,
        attendance_id: str,
        client_phone: str,
        last_attendance_summary: str = "",
        operational_state: str | None = None,
        attendance_context: str | None = None,
    ) -> Dict:
        """
        Process message using the agent
        
        Args:
            message_content: Message content (already formatted with tags)
            attendance_id: Attendance UUID
            client_phone: Client phone number
            last_attendance_summary: Resumo do último atendimento (quando atendimento atual é novo)
            operational_state: Estado operacional (TRIAGEM, ABERTO, etc.)
            attendance_context: novo | reaberto | em_andamento
            
        Returns:
            Dict with output and intermediate_steps
        """
        try:
            # Ensure tools are initialized before processing
            if not self._tools_initialized:
                await self.initialize_tools()
            
            import os
            worker_pid = os.getpid()
            logger.info(f"🤖 Agent processing message for attendance {attendance_id} [Worker PID: {worker_pid}]")
            
            # OPTIMIZATION: Check and create summary BEFORE processing (if needed)
            # This ensures summary is available for context building
            msg_count = await self.memory_manager.get_message_count(attendance_id)
            if msg_count and msg_count > 75:
                await self.memory_manager.check_and_create_summary_if_needed(attendance_id)
            
            # Build context using new rules (shared memory)
            context_data = await self.memory_manager.build_context_with_new_rules(
                attendance_id=attendance_id,
                client_phone=client_phone,
                current_message=message_content
            )
            
            recent_messages = context_data.get('recent_messages', '')
            intermediate_summary = context_data.get('intermediate_summary', '')
            rag_context = context_data.get('rag_context', '')
            open_cases = context_data.get('open_cases') or []
            
            # Verificar se atendimento está em TRIAGEM e buscar contexto histórico
            triagem_context = None
            try:
                attendance_state = await self.memory_manager.pg_client.fetchval("""
                    SELECT operational_state FROM attendances WHERE id = $1
                """, attendance_id)
                
                if attendance_state == 'TRIAGEM':
                    # Buscar whatsapp_number_id do atendimento
                    whatsapp_number_id = await self.memory_manager.pg_client.fetchval("""
                        SELECT whatsapp_number_id FROM attendances WHERE id = $1
                    """, attendance_id)
                    
                    if whatsapp_number_id:
                        triagem_context = await self.memory_manager.get_client_triagem_context(
                            client_phone=client_phone,
                            whatsapp_number_id=str(whatsapp_number_id),
                            current_attendance_id=attendance_id
                        )
            except Exception as e:
                logger.warning(f"Error fetching triagem context: {e}")
                triagem_context = None
            
            # Format system message with new structure - loads prompt from database
            # FORÇA reload para garantir prompt atualizado (cache desabilitado)
            system_message = await self.format_system_message_new_structure(
                recent_messages=recent_messages,
                intermediate_summary=intermediate_summary,
                rag_context=rag_context,
                last_attendance_summary=last_attendance_summary,
                open_cases=open_cases,
                attendance_id=attendance_id,
                triagem_context=triagem_context,
                operational_state=operational_state,
                attendance_context=attendance_context,
            )
            logger.debug(f"📝 System message length: {len(system_message)} chars for attendance {attendance_id}")
            
            # Buscar prompt configurado e universal
            configured_prompt = ""
            universal_prompt = ""
            try:
                agent_cfg = await self.agent_config_service.get_agent_config()
                configured_prompt = (agent_cfg or {}).get("prompt", "") or ""
                ma_config = await self.multi_agent_config_service.get_multi_agent_config() if self.multi_agent_config_service else None
                universal_prompt = (ma_config or {}).get("universal_prompt", "") or ""
            except Exception:
                pass

            # Se o usuário colou o universal dentro do prompt configurado, removemos APENAS
            # a ocorrência do universal configurado externamente (sem marcadores/regex).
            # Normalizamos espaços/linhas para comparação mais robusta
            configured_prompt_clean = configured_prompt
            if (universal_prompt or "").strip():
                universal_normalized = " ".join(universal_prompt.strip().split())
                configured_normalized = " ".join(configured_prompt.strip().split())
                # Se o universal normalizado está dentro do configured normalizado, remover
                if universal_normalized in configured_normalized:
                    # Remover do original (não normalizado) para preservar formatação
                    # Tentar remoção exata primeiro
                    if universal_prompt.strip() in configured_prompt:
                        configured_prompt_clean = configured_prompt.replace(universal_prompt.strip(), "").strip()
                    else:
                        # Se não encontrou exato, tentar com normalização de linhas
                        universal_lines = [l.strip() for l in universal_prompt.strip().split('\n') if l.strip()]
                        configured_lines = configured_prompt.split('\n')
                        # Remover linhas que correspondem ao universal
                        result_lines = []
                        i = 0
                        while i < len(configured_lines):
                            line = configured_lines[i].strip()
                            if universal_lines and line in universal_lines:
                                # Verificar se as próximas linhas também batem
                                match = True
                                for j, ul in enumerate(universal_lines):
                                    if i + j >= len(configured_lines) or configured_lines[i + j].strip() != ul:
                                        match = False
                                        break
                                if match:
                                    i += len(universal_lines)
                                    continue
                            result_lines.append(configured_lines[i])
                            i += 1
                        configured_prompt_clean = "\n".join(result_lines).strip()
            
            # Input direto - SEM regras hardcoded
            # Tudo deve vir do prompt configurado no Super Admin
            formatted_input = f"""{system_message}

Cliente: {message_content}"""

            usage_cb = TokenUsageCallback()
            invoke_config: Dict[str, Any] = {"callbacks": [usage_cb]}
            _log_ctx: Dict[str, Any] = {
                "configured_prompt": configured_prompt_clean,
                "universal_prompt": universal_prompt,
                "conversation_history": recent_messages,
                "system_additions": {
                    "intermediate_summary": intermediate_summary,
                    "rag_context": rag_context,
                    "last_attendance_summary": last_attendance_summary,
                    "open_cases": open_cases,
                    "triagem_context": triagem_context,
                    "operational_state": operational_state,
                    "attendance_context": attendance_context,
                },
                "message_content": message_content,
            }

            with get_openai_callback() as openai_cb:
                # Sem tools: 1 chamada com structured output (response + fragments)
                if not self.tools:
                    logger.info("⚡ NO TOOLS ACTIVE - Using LLM with structured output (1 call = response + fragments)")
                    structured_instruction = """Retorne sua resposta no formato estruturado: o campo "response" com o texto completo da sua resposta ao cliente, e o campo "fragments" com uma lista de segmentos (frases ou partes lógicas) que compõem essa resposta. IMPORTANTE: cada segmento em "fragments" deve incluir sua pontuação final (. , ! ?) conforme a frase original. NUNCA quebre horários, datas ou valores numéricos entre fragmentos diferentes (ex: "13:00", "18:30", "R$ 100,00" devem permanecer inteiros dentro do mesmo fragmento)."""

                    # Montagem final do SYSTEM: system_message primeiro (já contém XML), depois prompts do painel
                    # Ordem: Sistema -> Universal -> Especialista
                    parts = []
                    
                    # 1. System message completo (contém XML + contexto)
                    if system_message and system_message.strip():
                        parts.append(system_message.strip())
                    
                    # 2. Prompt universal (do painel) - ANTES do configurado
                    if universal_prompt and universal_prompt.strip():
                        parts.append(universal_prompt.strip())
                    
                    # 3. Prompt configurado (do painel) - DEPOIS do universal
                    if configured_prompt_clean and configured_prompt_clean.strip():
                        parts.append(configured_prompt_clean.strip())
                    
                    # 4. Instrução de formato estruturado
                    if structured_instruction and structured_instruction.strip():
                        parts.append(structured_instruction.strip())
                    
                    system_with_instruction = "\n\n".join(parts)
                    
                    # Log para debug
                    logger.info(f"📝 LangChain Agent prompt montado (NO TOOLS): System={len(system_message or '')} chars, Configured={len(configured_prompt_clean or '')} chars, Universal={len(universal_prompt or '')} chars, Total={len(system_with_instruction)} chars")

                    messages = [
                        SystemMessage(content=system_with_instruction),
                        HumanMessage(content=message_content)
                    ]
                    _log_ctx["system_context_text"] = system_message
                    _log_ctx["final_prompt"] = system_with_instruction
                    _log_ctx["prompt_sent"] = system_with_instruction
                    _log_ctx["messages_sent"] = messages
                    try:
                        parsed = await self.structured_llm.ainvoke(messages, config=invoke_config)
                    except Exception as e:
                        # Tratamento 1: Erro de temperatura não suportada
                        if _is_temperature_unsupported_error(e):
                            if temp_to_use != 1.0:
                                current_model = getattr(self, "_model_from_db", None) or settings.openai_model
                                logger.warning(f"Agent model {current_model} does not support temperature {temp_to_use}. Retrying with default temperature (1.0)")
                                self.llm = ChatOpenAI(
                                    model=current_model,
                                    temperature=1.0,  # Temperatura padrão obrigatória
                                    streaming=False,
                                    api_key=settings.openai_api_key,
                                    timeout=OPENAI_HTTP_TIMEOUT,
                                    max_retries=0,
                                )
                                self.structured_llm = self.llm.with_structured_output(
                                    FragmentedResponse,
                                    method="function_calling"
                                )
                                parsed = await self.structured_llm.ainvoke(messages, config=invoke_config)
                            else:
                                raise
                        # Tratamento 2: Fallback de modelo
                        elif _should_fallback_model(e):
                            current_model = getattr(self, "_model_from_db", None) or settings.openai_model
                            fb = _fallback_model(current_model)
                            if fb and fb != current_model:
                                logger.warning(f"Agent model not found. Falling back from {current_model} to {fb}")
                                self.llm = ChatOpenAI(
                                    model=fb,
                                    temperature=temp_to_use,
                                    streaming=False,
                                    api_key=settings.openai_api_key,
                                    timeout=OPENAI_HTTP_TIMEOUT,
                                    max_retries=0,
                                )
                                self.structured_llm = self.llm.with_structured_output(
                                    FragmentedResponse,
                                    method="function_calling"
                                )
                                parsed = await self.structured_llm.ainvoke(messages, config=invoke_config)
                                self._model_from_db = fb
                            else:
                                raise
                        else:
                            raise
                    output = parsed.response
                    fragments_from_structured = list(parsed.fragments) if parsed.fragments else [output]
                    intermediate_steps = []
                    result = {"output": output, "intermediate_steps": [], "_pre_fragmented": (output, fragments_from_structured)}
                else:
                    # Com tools: 1 chamada com bind_tools; modelo devolve content ou tool_calls
                    logger.info("⚡ SINGLE-CALL WITH TOOLS - 1 LLM call, then at most 1 tool execution")
                    
                    # Montagem final do SYSTEM: system_message primeiro (já contém XML), depois prompts do painel
                    # Ordem: Sistema -> Universal -> Especialista
                    parts = []
                    
                    # 1. System message completo (contém XML + contexto)
                    if system_message and system_message.strip():
                        parts.append(system_message.strip())
                    
                    # 2. Prompt universal (do painel) - ANTES do configurado
                    if universal_prompt and universal_prompt.strip():
                        parts.append(universal_prompt.strip())
                    
                    # 3. Prompt configurado (do painel) - DEPOIS do universal
                    if configured_prompt_clean and configured_prompt_clean.strip():
                        parts.append(configured_prompt_clean.strip())
                    
                    system_with_instruction = "\n\n".join(parts)
                    
                    # Log para debug
                    logger.info(f"📝 LangChain Agent prompt montado (WITH TOOLS): System={len(system_message or '')} chars, Configured={len(configured_prompt_clean or '')} chars, Universal={len(universal_prompt or '')} chars, Total={len(system_with_instruction)} chars")

                    messages = [
                        SystemMessage(content=system_with_instruction),
                        HumanMessage(content=message_content)
                    ]
                    _log_ctx["system_context_text"] = system_message
                    # system_final_instructions removido dos logs (já está no XML do system_message)
                    _log_ctx["final_prompt"] = system_with_instruction
                    _log_ctx["messages_sent"] = messages
                    llm_with_tools = self.llm.bind_tools(self.tools)
                    try:
                        response = await llm_with_tools.ainvoke(messages, config=invoke_config)
                    except Exception as e:
                        # Tratamento 1: Erro de temperatura não suportada
                        if _is_temperature_unsupported_error(e):
                            if temp_to_use != 1.0:
                                current_model = getattr(self, "_model_from_db", None) or settings.openai_model
                                logger.warning(f"Agent model {current_model} does not support temperature {temp_to_use}. Retrying with default temperature (1.0)")
                                self.llm = ChatOpenAI(
                                    model=current_model,
                                    temperature=1.0,  # Temperatura padrão obrigatória
                                    streaming=False,
                                    api_key=settings.openai_api_key,
                                    timeout=OPENAI_HTTP_TIMEOUT,
                                    max_retries=0,
                                )
                                self.structured_llm = self.llm.with_structured_output(
                                    FragmentedResponse,
                                    method="function_calling"
                                )
                                llm_with_tools = self.llm.bind_tools(self.tools)
                                response = await llm_with_tools.ainvoke(messages, config=invoke_config)
                            else:
                                raise
                        # Tratamento 2: Fallback de modelo
                        elif _should_fallback_model(e):
                            current_model = getattr(self, "_model_from_db", None) or settings.openai_model
                            fb = _fallback_model(current_model)
                            if fb and fb != current_model:
                                logger.warning(f"Agent model not found. Falling back from {current_model} to {fb}")
                                self.llm = ChatOpenAI(
                                    model=fb,
                                    temperature=temp_to_use,
                                    streaming=False,
                                    api_key=settings.openai_api_key,
                                    timeout=OPENAI_HTTP_TIMEOUT,
                                    max_retries=0,
                                )
                                self.structured_llm = self.llm.with_structured_output(
                                    FragmentedResponse,
                                    method="function_calling"
                                )
                                llm_with_tools = self.llm.bind_tools(self.tools)
                                response = await llm_with_tools.ainvoke(messages, config=invoke_config)
                                self._model_from_db = fb
                            else:
                                raise
                        else:
                            raise

                    output = (response.content or "").strip() if hasattr(response, "content") and response.content else ""
                    intermediate_steps = []
                    result = {"output": output, "intermediate_steps": []}

                    tool_calls = getattr(response, "tool_calls", None) or []
                    if not tool_calls and self.tools:
                        logger.info(
                            "Agent returned text only (no tool_calls). Tools available: %s — "
                            "LLM chose not to invoke any tool; process will not run.",
                            [t.name for t in self.tools],
                        )
                    if tool_calls:
                        tc = tool_calls[0]
                        tool_name = tc.get("name") if isinstance(tc, dict) else getattr(tc, "name", None)
                        args = tc.get("args") if isinstance(tc, dict) else getattr(tc, "args", None) or {}
                        if not isinstance(args, dict):
                            args = {}
                        tool = next((t for t in self.tools if t.name == tool_name), None)
                        if tool:
                            # Normalizar input: evitar ValidationError "Field required [data]" quando a LLM
                            # envia payload sem chave "data" (ex.: {"Resumo da conversa": "..."} ou {}).
                            tool_input = args
                            if isinstance(tool, DynamicFunctionCallTool):
                                # Se não tem "data" na chave, normaliza para {"data": args}
                                # Isso inclui o caso de args = {} -> {"data": {}}
                                if "data" not in args:
                                    tool_input = {"data": args}
                            try:
                                tool_result = await tool.ainvoke(tool_input)
                                if isinstance(tool_result, dict):
                                    import json
                                    tool_result = json.dumps(tool_result, ensure_ascii=False)
                                tool_result_str = str(tool_result) if tool_result is not None else ""
                            except Exception as tool_err:
                                logger.error(
                                    "Tool execution failed — cause logged for debugging",
                                    extra={
                                        "tool_name": tool_name,
                                        "args_keys": list(args.keys()) if isinstance(args, dict) else repr(type(args)),
                                        "error_type": type(tool_err).__name__,
                                        "error_message": str(tool_err),
                                    },
                                    exc_info=True,
                                )
                                tool_result_str = str(tool_err)
                            # Formato esperado por _process_function_calls e langgraph: step[0] com .tool e .tool_input, step[1] = resultado
                            class _ToolAction:
                                def __init__(self, name: str, tool_input: dict):
                                    self.tool = name
                                    self.tool_input = tool_input
                            action = _ToolAction(tool_name, args)
                            intermediate_steps = [(action, tool_result_str)]
                            result["intermediate_steps"] = intermediate_steps

                # Remove mensagens de erro do LangChain quando atinge limites
                if output and ("stopped due to iteration limit" in output.lower() or
                              "stopped due to time limit" in output.lower()):
                    limit_type = "iteration" if "iteration limit" in output.lower() else "time"
                    logger.error(f"❌ Agent hit {limit_type} limit for attendance {attendance_id}", extra={
                        "limit_type": limit_type,
                        "output_preview": output[:200],
                        "intermediate_steps_count": len(intermediate_steps),
                        "tools_count": len(self.tools),
                        "tools_names": [tool.name for tool in self.tools] if self.tools else [],
                        "message_content": message_content[:200],
                        "max_iterations": 15,
                        "max_execution_time": 45
                    })
                    output = ""

                if self.function_call_processor and intermediate_steps:
                    processed_output_from_tool = await self._process_function_calls(
                        intermediate_steps, attendance_id, client_phone, result
                    )
                    if processed_output_from_tool:
                        output = processed_output_from_tool

                if intermediate_steps:
                    logger.debug(f"Intermediate steps for attendance {attendance_id}: {len(intermediate_steps)} steps")
                    for idx, step in enumerate(intermediate_steps):
                        logger.debug(f"Step {idx}: {str(step)[:200]}")

                # Se executou tool mas não há output (ex.: processador não retornou texto), segunda chamada ao LLM para continuar conversa
                if intermediate_steps and (not output or output.strip() == ""):
                    logger.info(f"Agent executed tool but no output - making second LLM call to continue conversation for attendance {attendance_id}")
                    try:
                        tool_names = []
                        for step in intermediate_steps:
                            if len(step) >= 2:
                                action = step[0]
                                name = action.tool if hasattr(action, "tool") else (action.get("tool") if isinstance(action, dict) else "unknown")
                                tool_names.append(name)
                        tool_summary = ", ".join(tool_names) if tool_names else "ferramenta"
                        continue_messages = [
                            SystemMessage(content=system_with_instruction),
                            HumanMessage(content=message_content),
                            AIMessage(content=f"[Ferramenta executada: {tool_summary}.]"),
                            HumanMessage(
                                content="A ferramenta foi executada com sucesso. Responda ao cliente em uma única mensagem curta e objetiva, sem repetir a mesma informação. "
                                "Se foi pedido de orçamento, diga apenas uma vez que enviou o pedido para a equipe e que em breve retornará com o orçamento."
                            ),
                        ]
                        llm_continue = self.llm.bind_tools(self.tools) if self.tools else self.llm
                        continue_response = await llm_continue.ainvoke(continue_messages, config=invoke_config)
                        continue_output = (continue_response.content or "").strip() if getattr(continue_response, "content", None) else ""
                        if continue_output:
                            output = continue_output
                            logger.info(f"Agent continued conversation after tool execution for attendance {attendance_id}")
                        else:
                            output = "Enviei seu pedido de orçamento para nossa equipe. Assim que tivermos o orçamento pronto, já te retorno!"
                            logger.info(f"Using fallback message for attendance {attendance_id} (LLM returned empty)")
                    except Exception as e:
                        logger.error(f"Error making second LLM call after tool execution: {e}", exc_info=True)
                        output = "Enviei seu pedido de orçamento para nossa equipe. Assim que tivermos o orçamento pronto, já te retorno!"

                if not output or output.strip() == "":
                    logger.warning(f"Agent returned empty output for attendance {attendance_id}", extra={
                        "intermediate_steps_count": len(intermediate_steps),
                        "message_content": message_content[:200],
                        "tools_count": len(self.tools),
                        "tools_names": [tool.name for tool in self.tools] if self.tools else [],
                    })

                def _build_usage(out_len: int = 0) -> dict:
                    pt = usage_cb.prompt_tokens
                    ct = usage_cb.completion_tokens
                    tt = usage_cb.total_tokens
                    if tt <= 0 and (openai_cb.prompt_tokens or openai_cb.completion_tokens or openai_cb.total_tokens):
                        pt = openai_cb.prompt_tokens
                        ct = openai_cb.completion_tokens
                        tt = openai_cb.total_tokens or (pt + ct)
                    if tt <= 0:
                        est_pt = max(0, (len(system_message) + len(message_content)) // 4)
                        est_ct = max(0, out_len // 4)
                        pt = est_pt
                        ct = est_ct
                        tt = pt + ct
                        if tt > 0:
                            logger.info("Token usage not captured; using estimated tokens", extra={"prompt": pt, "completion": ct, "total": tt})
                    return {"prompt_tokens": pt, "completion_tokens": ct, "total_tokens": tt}

                try:
                    import re
                    logger.info(f"Processing agent output for attendance {attendance_id}")
                    logger.debug(f"Original output length: {len(output)} characters")

                    # Proteger URLs (com ou sem esquema) antes de fragmentar por pontuação.
                    url_pattern = re.compile(
                        r'(https?://\S+|'              # http/https
                        r'www\.\S+|'                   # começa com www.
                        r'\b[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\S*)'  # dominio.tld[/...]
                    )

                    def _protect_urls(text: str):
                        urls = url_pattern.findall(text)
                        mapping = {}
                        for i, u in enumerate(urls):
                            token = f"__URL_{i}__"
                            mapping[token] = u
                            text = text.replace(u, token)
                        return text, mapping

                    def _restore_urls(fragments_list, mapping):
                        restored = []
                        for f in fragments_list:
                            for token, url in mapping.items():
                                f = f.replace(token, url)
                            restored.append(f)
                        return restored

                    def _postprocess_fragments(fragments_list):
                        """
                        Reorganiza fragments para melhor UX no WhatsApp:
                        - Mantém cabeçalhos e textos gerais como estão.
                        - Separa tópicos/bullets em balões diferentes (linhas iniciadas por '-' ou '•').
                        - Mantém linhas auxiliares curtas como '(pode listar)' junto da pergunta anterior,
                          especialmente quando esta termina com '?'.
                        """
                        result = []
                        prev: Optional[str] = None

                        def _is_emoji_only(s: str) -> bool:
                            # Heurística simples: linha curta, sem letras/números, provavelmente apenas emojis/símbolos
                            s = s.strip()
                            if not s or len(s) > 8:
                                return False
                            return not any(ch.isalnum() for ch in s)

                        for frag in fragments_list:
                            lines = str(frag).split('\n')
                            current = None
                            for line in lines:
                                stripped = line.strip()
                                if not stripped:
                                    continue
                                # Se o fragmento inteiro é uma linha curta entre parênteses e
                                # o último resultado termina com "?", anexa ao balão anterior.
                                if (
                                    stripped.startswith('(')
                                    and len(stripped) <= 40
                                    and prev is not None
                                    and prev.rstrip().endswith('?')
                                ):
                                    prev = prev.rstrip() + ' ' + stripped
                                    result[-1] = prev
                                    continue
                                # Emojis sozinhos: se houver balão anterior, anexar para evitar balão gigante só de emoji
                                if _is_emoji_only(stripped) and prev is not None:
                                    prev = prev.rstrip() + ' ' + stripped
                                    result[-1] = prev
                                    continue
                                # Nova bullet: começa com "-" ou "•"
                                if stripped.startswith(('-', '•')):
                                    if current:
                                        result.append(current.strip())
                                    current = stripped
                                else:
                                    if current is None:
                                        current = stripped
                                    else:
                                        # Caso especial: linha curta entre parênteses logo após uma pergunta
                                        if stripped.startswith('(') and current.rstrip().endswith('?'):
                                            current = current.rstrip() + ' ' + stripped
                                        else:
                                            current = current + '\n' + stripped
                            if current:
                                result.append(current.strip())
                            if result:
                                prev = result[-1]
                        return result

                    pre_fragmented = result.get("_pre_fragmented")
                    if pre_fragmented is not None:
                        final_output, fragments = pre_fragmented
                        result.pop("_pre_fragmented", None)
                        if not fragments:
                            fragments = [final_output]
                        _usage = _build_usage(len(final_output))
                        fragments_metadata = {"fragments": fragments, "fragment_count": len(fragments), "from_structured_output": True}
                        logger.info(f"✅ Using pre-fragmented output from single structured call: {len(fragments)} fragments")
                        exec_log = await self._build_execution_log(
                            _log_ctx, _log_ctx.get("messages_sent"), result.get("intermediate_steps", [])
                        )
                        return {
                            "output": final_output,
                            "intermediate_steps": result.get("intermediate_steps", []),
                            "fragments": fragments,
                            "metadata": fragments_metadata,
                            "usage": _usage,
                            "execution_log": exec_log,
                        }

                    # Split after sentence-ending punctuation (! ? : or . not in a number),
                    # mas sem quebrar dentro de URLs.
                    protected_output, url_map = _protect_urls(output)
                    # ':' só conta como delimitador quando NÃO é 'ex:' nem está entre dígitos (ex: 13:00, 18:30).
                    _parts = re.split(r'([!?]|(?<!\d)\.(?!\d)|(?<![eE]x)(?<!\d):(?!\d))\s*', protected_output)
                    simple_fragments = []
                    i = 0
                    while i < len(_parts):
                        s = _parts[i].strip()
                        if i + 1 < len(_parts) and _parts[i + 1] in '!?:.':
                            delim = _parts[i + 1]
                            # Caso especial: ponto seguido imediatamente de um bloco entre parênteses.
                            if (
                                delim == '.'
                                and i + 2 < len(_parts)
                                and _parts[i + 2].lstrip().startswith('(')
                                and ')' in _parts[i + 2]
                            ):
                                frag = (s + delim + ' ' + _parts[i + 2].strip()).strip()
                                if frag:
                                    simple_fragments.append(frag)
                                i += 3
                            else:
                                frag = (s + delim).strip()
                                if frag:
                                    simple_fragments.append(frag)
                                i += 2
                        else:
                            if s:
                                simple_fragments.append(s)
                            i += 1
                    if not simple_fragments:
                        simple_fragments = [protected_output]
                    # Restaurar URLs originais em cada fragmento
                    simple_fragments = _restore_urls(simple_fragments, url_map)
                    # Pós-processar para separar bullets e anexar linhas auxiliares como "(pode listar)"
                    simple_fragments = _postprocess_fragments(simple_fragments)

                    final_output = output
                    fragments = simple_fragments
                    logger.info(f"✅ Regex fragmentation (no second LLM call): {len(fragments)} fragments")

                    if not fragments:
                        fragments = [final_output]
                    _usage = _build_usage(len(final_output))
                    fragments_metadata = {"fragments": fragments, "fragment_count": len(fragments), "from_structured_output": False}
                    exec_log = await self._build_execution_log(
                        _log_ctx, _log_ctx.get("messages_sent"), result.get("intermediate_steps", [])
                    )
                    return {
                        "output": final_output,
                        "intermediate_steps": result.get("intermediate_steps", []),
                        "fragments": fragments,
                        "metadata": fragments_metadata,
                        "usage": _usage,
                        "execution_log": exec_log,
                    }
                except Exception as structured_error:
                    logger.error(f"❌ Error processing output for attendance {attendance_id}: {structured_error}", exc_info=True)
                    import re as _re_fallback
                    # Fallback: ainda proteger URLs antes de fragmentar
                    url_pattern_fb = _re_fallback.compile(
                        r'(https?://\S+|'
                        r'www\.\S+|'
                        r'\b[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\S*)'
                    )

                    def _protect_urls_fb(text: str):
                        urls = url_pattern_fb.findall(text)
                        mapping = {}
                        for i, u in enumerate(urls):
                            token = f"__URL_FB_{i}__"
                            mapping[token] = u
                            text = text.replace(u, token)
                        return text, mapping

                    def _restore_urls_fb(fragments_list, mapping):
                        restored = []
                        for f in fragments_list:
                            for token, url in mapping.items():
                                f = f.replace(token, url)
                            restored.append(f)
                        return restored

                    protected_output_fb, url_map_fb = _protect_urls_fb(output)
                    # Split after ! ? : or . (not in number) - fixed-width safe; protege horários como 13:00
                    _parts = _re_fallback.split(r'([!?]|(?<!\d)\.(?!\d)|(?<![eE]x)(?<!\d):(?!\d))\s*', protected_output_fb)
                    simple_fragments = []
                    i = 0
                    while i < len(_parts):
                        s = _parts[i].strip()
                        if i + 1 < len(_parts) and _parts[i + 1] in '!?.':
                            frag = (s + _parts[i + 1]).strip()
                            if frag:
                                simple_fragments.append(frag)
                            i += 2
                        else:
                            if s:
                                simple_fragments.append(s)
                            i += 1
                    if not simple_fragments:
                        simple_fragments = [protected_output_fb]
                    simple_fragments = _restore_urls_fb(simple_fragments, url_map_fb)
                    logger.warning(f"Using fallback fragments: {len(simple_fragments)} fragments")
                    _usage = _build_usage(len(output))
                    exec_log = await self._build_execution_log(
                        _log_ctx, _log_ctx.get("messages_sent"), result.get("intermediate_steps", [])
                    )
                    return {
                        "output": output,
                        "intermediate_steps": result.get("intermediate_steps", []),
                        "fragments": simple_fragments,
                        "metadata": {"fallback": True, "fragment_count": len(simple_fragments)},
                        "usage": result.get("usage") or _usage,
                        "execution_log": exec_log,
                    }
            
        except Exception as e:
            logger.error(f"Error processing message with agent: {e}", exc_info=True)
            return {
                "output": "",
                "intermediate_steps": [],
                "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
                "execution_log": await self._build_execution_log({}, None, []),
            }
    
    async def _process_function_calls(
        self,
        intermediate_steps: List,
        attendance_id: str,
        client_phone: str,
        agent_result: Dict
    ) -> Optional[str]:
        """
        Processa function calls executadas pelo agente via RabbitMQ.

        Returns:
            Último processed_output não vazio quando has_output e is_sync; None caso contrário.
            Esse valor deve ser usado como resposta ao cliente quando has_output+is_sync.
        """
        last_processed_output: Optional[str] = None
        try:
            from utils.postgres_client import pg_client

            # Usa o pg_client global já conectado
            # O pg_client já deve estar conectado no main.py
            if not pg_client.pool:
                logger.warning("PostgreSQL client not connected, skipping function call processing")
                return None

            try:
                for step in intermediate_steps:
                    if not step or len(step) < 2:
                        continue
                    
                    # step[0] é a ação (tool call), step[1] é o resultado
                    action = step[0]
                    tool_result = step[1]
                    
                    # Extrai nome da tool
                    tool_name = None
                    if hasattr(action, 'tool'):
                        tool_name = action.tool
                    elif isinstance(action, dict) and 'tool' in action:
                        tool_name = action['tool']
                    
                    if not tool_name:
                        continue
                    
                    # CORREÇÃO 3: Verifica se a function call está ativa antes de processar
                    is_active = await self.agent_config_service.is_function_call_active(tool_name)
                    if not is_active:
                        logger.info(f"⏸️  Function call {tool_name} is inactive, skipping processing")
                        continue
                    
                    # Busca config da function call na tabela agent_function_calls (nova)
                    config_row = await pg_client.fetchrow(
                        """
                        SELECT has_output, processing_method
                        FROM agent_function_calls
                        WHERE name = $1 AND is_active = true
                        """,
                        tool_name
                    )
                    
                    if not config_row:
                        # Se não tem config na nova tabela, pula
                        logger.warning(f"⚠️  No config found for function call {tool_name}")
                        continue
                    
                    has_output = config_row['has_output']
                    is_sync = True  # agent_function_calls não tem is_sync; default sync
                    processing_method = (config_row['processing_method'] or 'RABBITMQ').upper()
                    
                    # Só processa se método for RABBITMQ
                    if processing_method != 'RABBITMQ':
                        logger.debug(f"Function call {tool_name} uses {processing_method}, skipping RabbitMQ processing")
                        continue
                    
                    # Sempre publica e processa na fila. has_output/is_sync só definem se o agente
                    # espera resposta processada para usar na mensagem ao cliente (sync) ou não.
                    processed_output = await self.function_call_processor.process_function_call(
                        function_call_name=tool_name,
                        result=str(tool_result) if tool_result else "",
                        attendance_id=attendance_id,
                        client_phone=client_phone,
                        has_output=has_output,
                        is_sync=is_sync
                    )
                    
                    # Se retornou output processado (has_output + sync), acumula para usar como resposta ao cliente
                    if processed_output:
                        last_processed_output = processed_output
                        logger.info(f"Function call {tool_name} processed, output: {processed_output[:100]}")

            finally:
                # Não fecha a conexão, pois é compartilhada
                pass

            return last_processed_output

        except Exception as e:
            logger.error(f"Error processing function calls: {e}", exc_info=True)
            # Não falha o processamento principal se houver erro aqui
            return None
