"""
Specialist Agent - Specialized agent for specific domain
Similar to AlteseAgent but uses domain-specific prompt and tools
"""
import httpx
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from tools.dynamic_function_call_tool import DynamicFunctionCallTool
from services.agent_config_service import AgentConfigService
from services.function_call_processor import FunctionCallProcessor
from services.multi_agent_config_service import MultiAgentConfigService
from langchain_community.callbacks.manager import get_openai_callback
from callbacks.token_usage_callback import TokenUsageCallback
from config.settings import settings
from utils.logger import logger
from utils.brasilia_time import get_brasilia_placeholders
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field

# Timeout para chamadas OpenAI
OPENAI_HTTP_TIMEOUT = httpx.Timeout(connect=15.0, read=90.0, write=30.0, pool=30.0)

def _should_fallback_model(exc: Exception) -> bool:
    name = exc.__class__.__name__
    msg = str(exc) or ""
    if name == "NotFoundError":
        return True
    if "model_not_found" in msg or "does not exist or you do not have access" in msg:
        return True
    return False

def _is_temperature_unsupported_error(exc: Exception) -> bool:
    """
    Detecta erro de temperatura não suportada (alguns modelos nano só aceitam temperatura padrão = 1.0).
    """
    name = exc.__class__.__name__
    msg = str(exc) or ""
    if name == "BadRequestError":
        if "temperature" in msg.lower() and ("does not support" in msg.lower() or "only the default" in msg.lower()):
            return True
    if "unsupported_value" in msg.lower() and "temperature" in msg.lower():
        return True
    return False

def _fallback_model(model: str | None) -> str | None:
    if not model:
        return model
    model_clean = model.strip()
    if model_clean == "gpt-4o-nano":
        return "gpt-4o-mini"
    if model_clean == "gpt-5-nano":
        return "gpt-4o-mini"  # Fallback para gpt-4o-mini também
    return model


class FragmentedResponse(BaseModel):
    """
    Structured output schema for fragmented responses
    """
    response: str = Field(description="The response that would be generated by the assistant.")
    fragments: List[str] = Field(description="All segments of the response generated by the assistant, dividing all the information. Never split times (13:00), dates, or monetary values across fragments.")
    
    model_config = {
        "extra": "forbid",
        "json_schema_extra": {
            "name": "fragmented_response",
            "strict": True
        }
    }


class SpecialistAgent:
    """
    Specialist Agent for specific domain
    Uses domain-specific prompt and only assigned function calls
    Shares memory with other agents
    """
    
    def __init__(
        self,
        specialist_config: Dict[str, Any],
        memory_manager,
        routing_service,
        agent_config_service: AgentConfigService,
        multi_agent_config_service: MultiAgentConfigService,
        function_call_processor: Optional[FunctionCallProcessor] = None
    ):
        self.specialist_config = specialist_config
        self.memory_manager = memory_manager
        self.routing_service = routing_service
        self.agent_config_service = agent_config_service
        self.multi_agent_config_service = multi_agent_config_service
        self.function_call_processor = function_call_processor
        
        # Initialize LLM with specialist's model and temperature
        self.llm = ChatOpenAI(
            model=specialist_config.get('model', 'gpt-4.1'),
            temperature=specialist_config.get('temperature', 0.7),
            streaming=False,
            api_key=settings.openai_api_key,
            timeout=OPENAI_HTTP_TIMEOUT,
            max_retries=0,
        )
        
        self.structured_llm = self.llm.with_structured_output(
            FragmentedResponse,
            method="function_calling"
        )
        
        # Tools will be loaded dynamically based on specialist's function_call_names
        self.tools: List[DynamicFunctionCallTool] = []
        self._tools_initialized = False
    
    async def initialize_tools(self):
        """Initialize tools assigned to this specialist"""
        if self._tools_initialized:
            return
        
        function_call_names = self.specialist_config.get('function_call_names', []) or []
        
        if not function_call_names:
            logger.info(f"Specialist '{self.specialist_config['name']}' has no function calls assigned")
            self.tools = []
            self._tools_initialized = True
            return
        
        logger.info(f"🔄 Loading {len(function_call_names)} function calls for specialist '{self.specialist_config['name']}'")
        
        # Load function calls data for assigned names only
        all_function_calls_data = await self.agent_config_service.get_active_function_calls_with_metadata()
        
        # Filter to only assigned function calls
        assigned_function_calls = [
            fc for fc in all_function_calls_data
            if fc['name'] in function_call_names
        ]
        
        if len(assigned_function_calls) < len(function_call_names):
            missing = set(function_call_names) - {fc['name'] for fc in assigned_function_calls}
            logger.warning(f"⚠️  Some function calls not found or inactive for specialist '{self.specialist_config['name']}': {missing}")
        
        # Create tools dynamically
        created_tools = []
        for fc_data in assigned_function_calls:
            try:
                tool = DynamicFunctionCallTool(
                    function_call_name=fc_data['name'],
                    description=fc_data['prompt'],
                    input_schema=fc_data.get('input_schema'),
                    required_fields=fc_data.get('required_fields') or [],
                    optional_fields=fc_data.get('optional_fields') or [],
                    agent_config_service=self.agent_config_service
                )
                created_tools.append(tool)
                logger.debug(f"✅ Created tool for specialist '{self.specialist_config['name']}': {fc_data['name']}")
            except Exception as e:
                logger.error(f"❌ Failed to create tool {fc_data['name']} for specialist '{self.specialist_config['name']}': {e}", exc_info=True)
        
        self.tools = created_tools
        self._tools_initialized = True
        tool_names = [t.name for t in self.tools] if self.tools else []
        logger.info(f"✅ Specialist '{self.specialist_config['name']}' initialized with {len(self.tools)} tools", extra={"tool_names": tool_names})
    
    async def format_system_message(self, chat_history: str, context: str) -> str:
        """Format system message with specialist prompt and context (legacy method)"""
        specialist_prompt = self.specialist_config.get('prompt', '')
        
        system_parts = [specialist_prompt]
        
        if context:
            system_parts.append(f"\nCONTEXTO ADICIONAL:\n{context}")
        
        if chat_history:
            system_parts.append(f"\nHISTÓRICO DA CONVERSA:\n{chat_history}")
        
        return "\n".join(system_parts)
    
    async def format_system_message_new_structure(
        self,
        recent_messages: str,
        intermediate_summary: str,
        rag_context: str,
        last_attendance_summary: str = "",
        open_cases: list = None,
        attendance_id: str = "",
        triagem_context: dict = None,
        operational_state: str | None = None,
        attendance_context: str | None = None,
    ) -> str:
        """Format system message with new context structure (SOMENTE contexto do sistema).
        
        IMPORTANTE: Não incluir prompt do painel aqui. O prompt do especialista e o prompt universal
        são concatenados externamente na montagem final do SYSTEM message, para termos separação
        determinística no execution_log.
        """
        system_parts = []
        
        # DATA E HORA ATUAL (Brasília) - SEMPRE presente para saudação e function calls (formato XML)
        try:
            ph = get_brasilia_placeholders()
            system_parts.append("")
            system_parts.append("<DataHoraAtual>")
            system_parts.append(f"  <Data>{ph.get('{{data_brasilia}}', 'N/A')}</Data>")
            system_parts.append(f"  <Horario>{ph.get('{{horario_brasilia}}', 'N/A')}</Horario>")
            system_parts.append(f"  <DiaSemana>{ph.get('{{dia_semana_brasilia}}', 'N/A')}</DiaSemana>")
            system_parts.append("  <Uso>Use para: saudação adequada (Bom dia / Boa tarde / Boa noite) e para function calls que dependam de data/hora.</Uso>")
            system_parts.append("</DataHoraAtual>")
        except Exception:
            pass  # não quebrar o fluxo se falhar
        
        # ESTRUTURA HIERÁRQUICA: ATENDIMENTO -> STATUS + MEMÓRIA
        # Iniciar estrutura XML do atendimento
        if attendance_id:
            system_parts.append("")
            system_parts.append("<Atendimento>")
            
            # STATUS DO ATENDIMENTO
            _state_labels = {
                "TRIAGEM": "em triagem (inicial)",
                "ABERTO": "aberto",
                "EM_ATENDIMENTO": "em atendimento (com vendedor)",
                "AGUARDANDO_CLIENTE": "aguardando resposta do cliente",
                "AGUARDANDO_VENDEDOR": "aguardando vendedor",
                "FECHADO_OPERACIONAL": "fechado",
            }
            _ctx_labels = {
                "novo": "Novo atendimento",
                "reaberto": "Atendimento reaberto (retomamos o anterior)",
                "em_andamento": "Conversa em andamento"
            }
            
            system_parts.append("  <Status>")
            if operational_state:
                label = _state_labels.get(operational_state, operational_state)
                system_parts.append(f"    <Estado>{label}</Estado>")
            else:
                system_parts.append("    <Estado>não especificado</Estado>")
            
            if attendance_context and attendance_context in _ctx_labels:
                system_parts.append(f"    <Contexto>{_ctx_labels[attendance_context]}</Contexto>")
            else:
                system_parts.append("    <Contexto>não especificado</Contexto>")
            
            system_parts.append("    <Instrucao>Use isso para decidir quando informar que retomamos o atendimento (reaberto), quando é novo ou em andamento. Não sugira 'abrir' atendimento se já estiver aberto ou em andamento.</Instrucao>")
            system_parts.append("  </Status>")
            
            # MEMÓRIA HIERÁRQUICA: RECENTES + RESUMO + RAG (dentro de Atendimento)
            system_parts.append("  <Memoria>")
            system_parts.append("    <Recentes tipo=\"curto-prazo\">")
            if recent_messages:
                system_parts.append("      <Conteudo>")
                for line in (recent_messages or "").strip().split("\n"):
                    system_parts.append("        " + line)
                system_parts.append("      </Conteudo>")
                system_parts.append("      <Descricao>Mensagens recentes da conversa atual (todas após a 10ª mensagem mais antiga do cliente)</Descricao>")
            else:
                system_parts.append("      <Conteudo>Primeiro contato do cliente.</Conteudo>")
                system_parts.append("      <Descricao>Nenhuma mensagem anterior no atendimento</Descricao>")
            system_parts.append("    </Recentes>")
            system_parts.append("    <Resumo tipo=\"medio-prazo\">")
            if intermediate_summary:
                system_parts.append("      <Conteudo>")
                for line in (intermediate_summary or "").strip().split("\n"):
                    system_parts.append("        " + line)
                system_parts.append("      </Conteudo>")
                system_parts.append("      <Descricao>Resumo das 30 mensagens do cliente antes da janela recente (gerado a cada 10 mensagens do cliente)</Descricao>")
            else:
                system_parts.append("      <Conteudo>Nenhum resumo disponível.</Conteudo>")
                system_parts.append("      <Descricao>Conversa ainda não possui histórico suficiente para resumo</Descricao>")
            system_parts.append("    </Resumo>")
            system_parts.append("    <RAG tipo=\"longo-prazo\">")
            if rag_context:
                system_parts.append("      <Conteudo>")
                for line in (rag_context or "").strip().split("\n"):
                    system_parts.append("        " + line)
                system_parts.append("      </Conteudo>")
                system_parts.append("      <Descricao>Contexto recuperado de até 100 atendimentos anteriores do cliente (acionado quando informação não está em Recentes nem em Resumo)</Descricao>")
            else:
                system_parts.append("      <Conteudo>Nenhum contexto histórico recuperado.</Conteudo>")
                system_parts.append("      <Descricao>Cliente não possui atendimentos anteriores relevantes ou informação já está em Recentes/Resumo</Descricao>")
            system_parts.append("    </RAG>")
            system_parts.append("  </Memoria>")
            if open_cases:
                system_parts.append("  <CasosAbertos>")
                for caso in open_cases:
                    type_label = caso.get('type_label', caso.get('type_key', ''))
                    title = caso.get('title') or 'Sem título'
                    status = caso.get('status', '')
                    system_parts.append(f"    <Caso tipo='{type_label}' status='{status}'>{title}</Caso>")
                system_parts.append("    <Descricao>Situações criadas por function calls que precisam de resposta humana (vendedor/supervisor)</Descricao>")
                system_parts.append("  </CasosAbertos>")
            system_parts.append("</Atendimento>")
        
        # Informações de triagem (quando atendimento está em TRIAGEM)
        if triagem_context:
            triagem_info = []
            
            # Verificar se tem atendimentos anteriores
            if triagem_context.get('has_previous_attendances'):
                closed_count = len(triagem_context.get('closed_attendances', []))
                triagem_info.append(f"O cliente possui {closed_count} atendimento(s) anterior(es) fechado(s).")
            
            # Verificar atendimentos em aberto
            if triagem_context.get('has_open_attendances'):
                open_attendances = triagem_context.get('open_attendances', [])
                triagem_info.append(f"\n⚠️ ATENÇÃO: O cliente possui {len(open_attendances)} atendimento(s) em aberto:")
                for att in open_attendances:
                    state = att.get('operational_state', 'DESCONHECIDO')
                    cases = att.get('open_cases', [])
                    incomplete = att.get('incomplete_process', False)
                    
                    info_line = f"- Atendimento #{att.get('id', 'N/A')[:8]}... (Estado: {state})"
                    if cases:
                        case_types = [c.get('type_label', c.get('type_key', '')) for c in cases]
                        info_line += f" com {len(cases)} caso(s) aberto(s): {', '.join(case_types)}"
                    if incomplete:
                        info_line += " [PROCESSO INCOMPLETO - cliente parou no meio]"
                    triagem_info.append(info_line)
            
            # Verificar últimos 3 atendimentos com casos abertos
            recent_with_cases = triagem_context.get('recent_with_open_cases', [])
            if recent_with_cases:
                triagem_info.append(f"\n📋 Nos últimos 3 atendimentos, há casos em aberto:")
                for att in recent_with_cases:
                    cases = att.get('open_cases', [])
                    case_types = [c.get('type_label', c.get('type_key', '')) for c in cases]
                    triagem_info.append(f"- Atendimento #{att.get('id', 'N/A')[:8]}...: {', '.join(case_types)}")
            
            # Verificar se parou no meio de algum processo
            if triagem_context.get('last_3_has_incomplete'):
                triagem_info.append(f"\n⏸️ O cliente parou no meio de algum processo em atendimento(s) anterior(es).")
            
            if triagem_info:
                system_parts.append("\n### CONTEXTO DE TRIAGEM - HISTÓRICO DO CLIENTE")
                system_parts.append("\n".join(triagem_info))
                system_parts.append("\n⚠️ IMPORTANTE: Use essas informações para perguntar ao cliente se ele quer:")
                system_parts.append("- Reabrir um atendimento antigo")
                system_parts.append("- Continuar um atendimento que está em aberto")
                system_parts.append("- Ou iniciar um novo atendimento")
                system_parts.append("Só pode haver UM atendimento ativo por cliente. Se o cliente escolher continuar/reabrir, você deve usar a function call apropriada para isso.")
        
        # Resumo do último atendimento (quando atendimento atual é novo e cliente tinha atendimentos finalizados)
        if last_attendance_summary and last_attendance_summary.strip():
            system_parts.append(f"\n### Resumo do último atendimento do cliente\n{last_attendance_summary.strip()}")
        
        # IMPORTANTE: Instruções sobre tags de mensagem (SEMPRE presente em todos os agentes) - formato XML
        # Esta seção deve estar presente em 100% dos prompts - informação do sistema
        system_parts.append("")
        system_parts.append("<Importante>")
        system_parts.append("  <Instrucao>As tags &lt;Text&gt;, &lt;Audio&gt;, &lt;Image&gt; indicam o tipo original da mensagem que você recebeu. INTERPRETE o conteúdo como se você tivesse realmente ouvido o áudio (quando marcado como &lt;Audio&gt;) ou visto a imagem (quando marcado como &lt;Image&gt;). NÃO trate como uma transcrição ou descrição - responda como se tivesse experiência direta com o conteúdo original.</Instrucao>")
        system_parts.append("  <Instrucao>Você NÃO deve retornar essas tags na sua resposta. Responda normalmente ou acione a ferramenta indicada pelos gatilhos do prompt.</Instrucao>")
        system_parts.append("</Importante>")

        # DadosParaOrcamento: variáveis dinâmicas (Capturados, UltimoEnviado) da FC pedido-orcamento
        if attendance_id:
            dados_orcamento_xml = await self.memory_manager.get_dados_para_orcamento_xml(attendance_id)
            if dados_orcamento_xml:
                system_parts.append(dados_orcamento_xml)

        return "\n".join(system_parts).strip()
    
    # NOTE: separação por parsing do texto foi removida.
    # A separação Painel (especialista/universal) deve vir de fontes externas (config do painel),
    # não do conteúdo do prompt, pois o texto pode mudar.
    
    async def _build_execution_log(
        self,
        context_parts: dict | None,
        messages_sent: list | None,
        intermediate_steps: list,
    ) -> dict:
        """Build execution_log for Custos → Ver Log da Execução.
        
        Args:
            context_parts: dict with keys:
                - configured_prompt: prompt configurado no painel
                - universal_prompt: prompt universal (se existir)
                - conversation_history: histórico de mensagens
                - system_additions: dict com {summary, rag, cases, triagem, status}
                - final_prompt: prompt final montado
                - message_content: mensagem atual do cliente
            messages_sent: lista de mensagens enviadas ao LLM
            intermediate_steps: passos intermediários (tools)
        """
        import json as _json
        out: Dict[str, Any] = {}
        
        # 1. Prompt configurado no painel (do especialista) - vem do painel (fonte externa)
        if context_parts and context_parts.get("configured_prompt"):
            out["configuredPrompt"] = context_parts["configured_prompt"]
        
        # 2. Prompt universal (se existir)
        if context_parts and context_parts.get("universal_prompt"):
            out["universalPrompt"] = context_parts["universal_prompt"]
        
        # 3. Histórico da conversa (mensagens anteriores reais)
        if context_parts and context_parts.get("conversation_history"):
            out["conversationHistory"] = context_parts["conversation_history"]
        
        # 4. Contexto adicionado pelo sistema
        if context_parts and context_parts.get("system_additions"):
            out["systemAdditions"] = context_parts["system_additions"]

        # 4.1 Texto do contexto montado pelo sistema (separado, sem parsing)
        if context_parts and context_parts.get("system_context_text"):
            out["systemContextText"] = context_parts["system_context_text"]

        # 4.2 Instruções finais adicionadas pelo sistema - REMOVIDO DOS LOGS (já exibidas no sistema)
        # As instruções finais ainda são enviadas ao LLM, mas não aparecem nos logs
        
        # 5. Prompt final montado (tudo junto)
        if context_parts and context_parts.get("final_prompt"):
            out["finalPrompt"] = context_parts["final_prompt"]
        
        # 6. Payload OpenAI (formato exato enviado)
        if messages_sent:
            openai_messages = []
            for m in messages_sent:
                c = (m.content or "") if hasattr(m, "content") else ""
                role = "system" if isinstance(m, SystemMessage) else ("user" if isinstance(m, HumanMessage) else "assistant")
                openai_messages.append({"role": role, "content": c})
            # Capturar metadados do LLM
            llm_metadata = {}
            if hasattr(self.llm, "model_name"):
                llm_metadata["model"] = self.llm.model_name
            elif hasattr(self.llm, "model"):
                llm_metadata["model"] = self.llm.model
            else:
                llm_metadata["model"] = self.specialist_config.get('model', 'gpt-4.1')
            if hasattr(self.llm, "temperature"):
                llm_metadata["temperature"] = self.llm.temperature
            else:
                llm_metadata["temperature"] = self.specialist_config.get('temperature', 0.7)
            if hasattr(self.llm, "max_tokens"):
                llm_metadata["max_tokens"] = self.llm.max_tokens
            if hasattr(self.llm, "top_p"):
                llm_metadata["top_p"] = self.llm.top_p
            if hasattr(self.llm, "frequency_penalty"):
                llm_metadata["frequency_penalty"] = self.llm.frequency_penalty
            if hasattr(self.llm, "presence_penalty"):
                llm_metadata["presence_penalty"] = self.llm.presence_penalty
            out["openaiPayload"] = {
                **llm_metadata,
                "messages": openai_messages,
            }
        
        # Tools disponíveis
        tools_av = []
        for t in (self.tools or []):
            name = getattr(t, "name", None) or "?"
            desc = (getattr(t, "description", None) or "")[:500]
            schema = {}
            if hasattr(t, "args_schema") and t.args_schema is not None:
                try:
                    if hasattr(t.args_schema, "model_json_schema"):
                        schema = t.args_schema.model_json_schema()
                    elif hasattr(t.args_schema, "schema"):
                        schema = getattr(t.args_schema, "schema")() if callable(getattr(t.args_schema, "schema")) else {}
                    else:
                        schema = {}
                except Exception:
                    schema = {}
            tools_av.append({"name": name, "description": desc, "parameters": schema})
        out["toolsAvailable"] = tools_av
        out["specialist"] = {"name": self.specialist_config.get("name", "Unknown")}
        
        # Tools utilizadas
        tools_used = []
        for step in (intermediate_steps or []):
            if not step or len(step) < 2:
                continue
            action, res = step[0], step[1]
            name = getattr(action, "tool", None) or (action.get("tool") if isinstance(action, dict) else "?")
            args = getattr(action, "tool_input", None) or (action.get("tool_input") if isinstance(action, dict) else {})
            if not isinstance(args, dict):
                args = {}
            result_str = str(res) if res is not None else ""
            try:
                args = _json.loads(_json.dumps(args, default=str))
            except Exception:
                pass
            tools_used.append({"name": name, "arguments": args, "result": result_str[:2000], "success": "error" not in result_str.lower()})
        out["toolsUsed"] = tools_used
        return out
    
    async def process_message(
        self,
        message_content: str,
        attendance_id: str,
        client_phone: str,
        last_attendance_summary: str = "",
        operational_state: str | None = None,
        attendance_context: str | None = None,
    ) -> Dict:
        """
        Process message using the specialist agent
        
        Args:
            message_content: Message content (already formatted with tags)
            attendance_id: Attendance UUID
            client_phone: Client phone number
            last_attendance_summary: Resumo do último atendimento (quando atendimento atual é novo)
            operational_state: Estado operacional (TRIAGEM, ABERTO, etc.)
            attendance_context: novo | reaberto | em_andamento
            
        Returns:
            Dict with output, intermediate_steps, fragments, usage
        """
        try:
            # Ensure tools are initialized
            if not self._tools_initialized:
                await self.initialize_tools()
            
            import os
            worker_pid = os.getpid()
            specialist_name = self.specialist_config.get('name', 'Unknown')
            logger.info(f"🤖 Specialist '{specialist_name}' processing message for attendance {attendance_id} [Worker PID: {worker_pid}]")
            
            # Build context using new rules (shared memory)
            context_data = await self.memory_manager.build_context_with_new_rules(
                attendance_id=attendance_id,
                client_phone=client_phone,
                current_message=message_content
            )
            
            recent_messages = context_data.get('recent_messages', '')
            intermediate_summary = context_data.get('intermediate_summary', '')
            rag_context = context_data.get('rag_context', '')
            open_cases = context_data.get('open_cases') or []
            
            # Verificar se atendimento está em TRIAGEM e buscar contexto histórico
            triagem_context = None
            try:
                attendance_state = await self.memory_manager.pg_client.fetchval("""
                    SELECT operational_state FROM attendances WHERE id = $1
                """, attendance_id)
                
                if attendance_state == 'TRIAGEM':
                    # Buscar whatsapp_number_id do atendimento
                    whatsapp_number_id = await self.memory_manager.pg_client.fetchval("""
                        SELECT whatsapp_number_id FROM attendances WHERE id = $1
                    """, attendance_id)
                    
                    if whatsapp_number_id:
                        triagem_context = await self.memory_manager.get_client_triagem_context(
                            client_phone=client_phone,
                            whatsapp_number_id=str(whatsapp_number_id),
                            current_attendance_id=attendance_id
                        )
            except Exception as e:
                logger.warning(f"Error fetching triagem context: {e}")
                triagem_context = None
            
            # Format system message with new structure
            system_message = await self.format_system_message_new_structure(
                recent_messages=recent_messages,
                intermediate_summary=intermediate_summary,
                rag_context=rag_context,
                last_attendance_summary=last_attendance_summary,
                open_cases=open_cases,
                attendance_id=attendance_id,
                triagem_context=triagem_context,
                operational_state=operational_state,
                attendance_context=attendance_context,
            )
            logger.debug(f"📝 Specialist '{specialist_name}' system message length: {len(system_message)} chars")
            
            # Buscar prompt universal (se configurado) - SEMPRE buscar do painel (fonte externa)
            universal_prompt = ""
            try:
                universal_prompt = await self.multi_agent_config_service.get_universal_prompt()
            except Exception:
                pass
            
            usage_cb = TokenUsageCallback()
            invoke_config: Dict[str, Any] = {"callbacks": [usage_cb]}

            # Separação por fonte EXTERNA ao texto:
            # - configured_prompt: prompt do especialista configurado no painel
            # - universal_prompt: prompt universal configurado no painel (multi_agent_config)
            # OBS: agora o multi_agent_config_service retorna prompt do especialista SEM o universal.
            configured_prompt_raw = (self.specialist_config.get('prompt', '') or "")

            # IMPORTANTE: Se o universal está configurado no painel, ele SEMPRE deve aparecer separado.
            # Se o usuário colou o universal dentro do prompt do especialista, removemos para evitar duplicação.
            configured_prompt_clean = configured_prompt_raw
            if (universal_prompt or "").strip():
                # Normalizar para comparação (remover espaços extras, mas manter estrutura)
                universal_normalized = "\n".join([l.strip() for l in universal_prompt.strip().split('\n') if l.strip()])
                configured_normalized = "\n".join([l.strip() for l in configured_prompt_raw.strip().split('\n') if l.strip()])
                
                # Se o universal normalizado está dentro do configured normalizado, remover
                if universal_normalized in configured_normalized:
                    # Tentar remoção exata primeiro (preserva formatação)
                    if universal_prompt.strip() in configured_prompt_raw:
                        configured_prompt_clean = configured_prompt_raw.replace(universal_prompt.strip(), "").strip()
                    else:
                        # Remoção por linhas (mais robusta para diferenças de espaços)
                        universal_lines = [l.strip() for l in universal_prompt.strip().split('\n') if l.strip()]
                        configured_lines = configured_prompt_raw.split('\n')
                        result_lines = []
                        i = 0
                        while i < len(configured_lines):
                            # Verificar se a partir desta linha começa o universal
                            match_found = False
                            if i + len(universal_lines) <= len(configured_lines):
                                potential_match = [l.strip() for l in configured_lines[i:i+len(universal_lines)] if l.strip()]
                                if potential_match == universal_lines:
                                    match_found = True
                                    i += len(universal_lines)
                            if not match_found:
                                result_lines.append(configured_lines[i])
                                i += 1
                        configured_prompt_clean = "\n".join(result_lines).strip()
            
            # Garantir que universal_prompt sempre seja passado se existir (mesmo que vazio, para debug)
            logger.debug(f"📋 Specialist '{specialist_name}' - Universal prompt length: {len(universal_prompt or '')}, Configured prompt length: {len(configured_prompt_clean or '')}")
            
            _log_ctx: Dict[str, Any] = {
                "configured_prompt": configured_prompt_clean,  # Prompt do especialista (Painel) - SEM universal
                "universal_prompt": universal_prompt or "",  # Universal separado (SEMPRE do painel, nunca vazio se configurado)
                "conversation_history": recent_messages,
                "system_additions": {
                    "intermediate_summary": intermediate_summary,
                    "rag_context": rag_context,
                    "last_attendance_summary": last_attendance_summary,
                    "open_cases": open_cases,
                    "triagem_context": triagem_context,
                    "operational_state": operational_state,
                    "attendance_context": attendance_context,
                },
                "message_content": message_content,
            }
            
            with get_openai_callback() as openai_cb:
                
                # Without tools: use structured output
                if not self.tools:
                    logger.info(f"⚡ Specialist '{specialist_name}' - NO TOOLS - Using structured output")
                    structured_instruction = """Retorne sua resposta no formato estruturado: o campo "response" com o texto completo da sua resposta ao cliente, e o campo "fragments" com uma lista de segmentos (frases ou partes lógicas) que compõem essa resposta. IMPORTANTE: cada segmento em "fragments" deve incluir sua pontuação final (. , ! ?) conforme a frase original. NUNCA quebre horários, datas ou valores numéricos entre fragmentos diferentes (ex: "13:00", "18:30", "R$ 100,00" devem permanecer inteiros dentro do mesmo fragmento)."""

                    # Montagem final do SYSTEM: system_message primeiro (já contém XML), depois prompts do painel
                    # Ordem: Sistema -> Universal -> Especialista
                    parts = []
                    
                    # 1. System message completo (contém XML + contexto)
                    if system_message and system_message.strip():
                        parts.append(system_message.strip())
                    
                    # 2. Prompt universal (do painel) - ANTES do especialista
                    if universal_prompt and universal_prompt.strip():
                        parts.append(universal_prompt.strip())
                    
                    # 3. Prompt do especialista (do painel) - DEPOIS do universal
                    if configured_prompt_clean and configured_prompt_clean.strip():
                        parts.append(configured_prompt_clean.strip())
                    
                    # 4. Instrução de formato estruturado
                    if structured_instruction and structured_instruction.strip():
                        parts.append(structured_instruction.strip())
                    
                    system_with_instruction = "\n\n".join(parts)
                    
                    # Log para debug
                    logger.info(f"📝 Specialist '{specialist_name}' prompt montado: System={len(system_message or '')} chars, Specialist={len(configured_prompt_clean or '')} chars, Universal={len(universal_prompt or '')} chars, Total={len(system_with_instruction)} chars")

                    messages = [
                        SystemMessage(content=system_with_instruction),
                        HumanMessage(content=message_content)
                    ]
                    _log_ctx["system_context_text"] = system_message
                    _log_ctx["final_prompt"] = system_with_instruction
                    _log_ctx["prompt_sent"] = system_with_instruction
                    _log_ctx["messages_sent"] = messages
                    try:
                        parsed = await self.structured_llm.ainvoke(messages, config=invoke_config)
                    except Exception as e:
                        # Tratamento 1: Erro de temperatura não suportada
                        if _is_temperature_unsupported_error(e):
                            current_temp = self.specialist_config.get('temperature', 0.7)
                            if current_temp != 1.0:
                                logger.warning(f"Specialist '{specialist_name}' model {self.specialist_config.get('model')} does not support temperature {current_temp}. Retrying with default temperature (1.0)")
                                self.llm = ChatOpenAI(
                                    model=self.specialist_config.get('model', 'gpt-4.1'),
                                    temperature=1.0,  # Temperatura padrão obrigatória
                                    streaming=False,
                                    api_key=settings.openai_api_key,
                                    timeout=OPENAI_HTTP_TIMEOUT,
                                    max_retries=0,
                                )
                                self.structured_llm = self.llm.with_structured_output(
                                    FragmentedResponse,
                                    method="function_calling"
                                )
                                parsed = await self.structured_llm.ainvoke(messages, config=invoke_config)
                            else:
                                raise
                        # Tratamento 2: Fallback de modelo
                        elif _should_fallback_model(e):
                            current_model = self.specialist_config.get('model', 'gpt-4.1')
                            fb = _fallback_model(current_model)
                            if fb and fb != current_model:
                                logger.warning(f"Specialist model not found. Falling back from {current_model} to {fb}")
                                self.llm = ChatOpenAI(
                                    model=fb,
                                    temperature=self.specialist_config.get('temperature', 0.7),
                                    streaming=False,
                                    api_key=settings.openai_api_key,
                                    timeout=OPENAI_HTTP_TIMEOUT,
                                    max_retries=0,
                                )
                                self.structured_llm = self.llm.with_structured_output(
                                    FragmentedResponse,
                                    method="function_calling"
                                )
                                parsed = await self.structured_llm.ainvoke(messages, config=invoke_config)
                                self.specialist_config['model'] = fb
                            else:
                                raise
                        else:
                            raise
                    output = parsed.response
                    fragments_from_structured = list(parsed.fragments) if parsed.fragments else [output]
                    intermediate_steps = []
                    result = {"output": output, "intermediate_steps": [], "_pre_fragmented": (output, fragments_from_structured)}
                else:
                    # With tools: single call with bind_tools
                    logger.info(f"⚡ Specialist '{specialist_name}' - WITH TOOLS ({len(self.tools)} tools) - Single call")
                    
                    # Montagem final do SYSTEM: system_message primeiro (já contém XML), depois prompts do painel
                    # Ordem: Sistema -> Universal -> Especialista
                    parts = []
                    
                    # 1. System message completo (contém XML + contexto)
                    if system_message and system_message.strip():
                        parts.append(system_message.strip())
                    
                    # 2. Prompt universal (do painel) - ANTES do especialista
                    if universal_prompt and universal_prompt.strip():
                        parts.append(universal_prompt.strip())
                    
                    # 3. Prompt do especialista (do painel) - DEPOIS do universal
                    if configured_prompt_clean and configured_prompt_clean.strip():
                        parts.append(configured_prompt_clean.strip())
                    
                    system_with_instruction = "\n\n".join(parts)
                    
                    # Log para debug
                    logger.info(f"📝 Specialist '{specialist_name}' prompt montado (WITH TOOLS): System={len(system_message or '')} chars, Specialist={len(configured_prompt_clean or '')} chars, Universal={len(universal_prompt or '')} chars, Total={len(system_with_instruction)} chars")

                    messages = [
                        SystemMessage(content=system_with_instruction),
                        HumanMessage(content=message_content)
                    ]
                    _log_ctx["system_context_text"] = system_message
                    # system_final_instructions removido dos logs (já está no XML do system_message)
                    _log_ctx["final_prompt"] = system_with_instruction
                    _log_ctx["messages_sent"] = messages
                    llm_with_tools = self.llm.bind_tools(self.tools)
                    try:
                        response = await llm_with_tools.ainvoke(messages, config=invoke_config)
                    except Exception as e:
                        # Tratamento 1: Erro de temperatura não suportada
                        if _is_temperature_unsupported_error(e):
                            current_temp = self.specialist_config.get('temperature', 0.7)
                            if current_temp != 1.0:
                                logger.warning(f"Specialist '{specialist_name}' model {self.specialist_config.get('model')} does not support temperature {current_temp}. Retrying with default temperature (1.0)")
                                self.llm = ChatOpenAI(
                                    model=self.specialist_config.get('model', 'gpt-4.1'),
                                    temperature=1.0,  # Temperatura padrão obrigatória
                                    streaming=False,
                                    api_key=settings.openai_api_key,
                                    timeout=OPENAI_HTTP_TIMEOUT,
                                    max_retries=0,
                                )
                                self.structured_llm = self.llm.with_structured_output(
                                    FragmentedResponse,
                                    method="function_calling"
                                )
                                llm_with_tools = self.llm.bind_tools(self.tools)
                                response = await llm_with_tools.ainvoke(messages, config=invoke_config)
                            else:
                                raise
                        # Tratamento 2: Fallback de modelo
                        elif _should_fallback_model(e):
                            current_model = self.specialist_config.get('model', 'gpt-4.1')
                            fb = _fallback_model(current_model)
                            if fb and fb != current_model:
                                logger.warning(f"Specialist model not found. Falling back from {current_model} to {fb}")
                                self.llm = ChatOpenAI(
                                    model=fb,
                                    temperature=self.specialist_config.get('temperature', 0.7),
                                    streaming=False,
                                    api_key=settings.openai_api_key,
                                    timeout=OPENAI_HTTP_TIMEOUT,
                                    max_retries=0,
                                )
                                self.structured_llm = self.llm.with_structured_output(
                                    FragmentedResponse,
                                    method="function_calling"
                                )
                                llm_with_tools = self.llm.bind_tools(self.tools)
                                response = await llm_with_tools.ainvoke(messages, config=invoke_config)
                                self.specialist_config['model'] = fb
                            else:
                                raise
                        else:
                            raise
                    
                    output = (response.content or "").strip() if hasattr(response, "content") and response.content else ""
                    intermediate_steps = []
                    result = {"output": output, "intermediate_steps": []}
                    
                    tool_calls = getattr(response, "tool_calls", None) or []
                    if tool_calls:
                        tc = tool_calls[0]
                        tool_name = tc.get("name") if isinstance(tc, dict) else getattr(tc, "name", None)
                        logger.info(f"🔧 Specialist '{specialist_name}' invoked tool: {tool_name}", extra={"attendance_id": attendance_id})
                        args = tc.get("args") if isinstance(tc, dict) else getattr(tc, "args", None) or {}
                        if not isinstance(args, dict):
                            args = {}
                        tool = next((t for t in self.tools if t.name == tool_name), None)
                        if tool:
                            # Normalizar input: evitar ValidationError "Field required [data]" quando a LLM
                            # envia payload sem chave "data" (ex.: {"Resumo da conversa": "..."} ou {}).
                            tool_input = args
                            if isinstance(tool, DynamicFunctionCallTool):
                                # Se não tem "data" na chave, normaliza para {"data": args}
                                # Isso inclui o caso de args = {} -> {"data": {}}
                                if "data" not in args:
                                    tool_input = {"data": args}
                            try:
                                tool_result = await tool.ainvoke(tool_input)
                                if isinstance(tool_result, dict):
                                    import json
                                    tool_result = json.dumps(tool_result, ensure_ascii=False)
                                tool_result_str = str(tool_result) if tool_result is not None else ""
                            except Exception as tool_err:
                                logger.error(
                                    "Tool execution failed — cause logged for debugging",
                                    extra={
                                        "tool_name": tool_name,
                                        "args_keys": list(args.keys()) if isinstance(args, dict) else repr(type(args)),
                                        "error_type": type(tool_err).__name__,
                                        "error_message": str(tool_err),
                                        "specialist": specialist_name,
                                    },
                                    exc_info=True,
                                )
                                tool_result_str = str(tool_err)
                            
                            class _ToolAction:
                                def __init__(self, name: str, tool_input: dict):
                                    self.tool = name
                                    self.tool_input = tool_input
                            
                            action = _ToolAction(tool_name, args)
                            intermediate_steps = [(action, tool_result_str)]
                            result["intermediate_steps"] = intermediate_steps
                    elif self.tools:
                        logger.info(
                            f"Specialist '{specialist_name}' returned text only (no tool_calls) — tools disponíveis: {[t.name for t in self.tools]}",
                            extra={"attendance_id": attendance_id},
                        )
                
                # Process function calls if any
                if self.function_call_processor and intermediate_steps:
                    processed_output_from_tool = await self._process_function_calls(
                        intermediate_steps, attendance_id, client_phone, result
                    )
                    if processed_output_from_tool:
                        output = processed_output_from_tool
                        result["output"] = output
                
                # Se executou tool mas não há output, fazer segunda chamada ao LLM para continuar conversa
                if intermediate_steps and (not output or output.strip() == ""):
                    logger.info(f"Specialist '{specialist_name}' executed tool but no output - making second LLM call to continue conversation")
                    try:
                        # Adiciona resultado da tool ao contexto e pede para continuar
                        tool_result_summary = ""
                        for step in intermediate_steps:
                            if len(step) >= 2:
                                action = step[0]
                                tool_result = step[1]
                                tool_name = action.tool if hasattr(action, 'tool') else (action.get('tool') if isinstance(action, dict) else 'unknown')
                                tool_result_summary += f"A ferramenta '{tool_name}' foi executada com sucesso. "
                        
                        # Faz segunda chamada ao LLM com contexto da tool executada
                        continue_messages = [
                            SystemMessage(content=system_message),
                            HumanMessage(content=message_content),
                            AIMessage(content=f"[Ferramenta executada: {tool_result_summary.strip()}]"),
                            HumanMessage(content="Continue a conversa respondendo ao cliente em uma única mensagem curta e objetiva, sem repetir a mesma informação.")
                        ]
                        
                        llm_with_tools_continue = self.llm.bind_tools(self.tools) if self.tools else self.llm
                        continue_response = await llm_with_tools_continue.ainvoke(continue_messages, config=invoke_config)
                        continue_output = (continue_response.content or "").strip() if hasattr(continue_response, "content") and continue_response.content else ""
                        
                        if continue_output:
                            output = continue_output
                            result["output"] = output
                            logger.info(f"Specialist '{specialist_name}' continued conversation after tool execution")
                        else:
                            logger.warning(f"Specialist '{specialist_name}' second LLM call also returned empty output")
                    except Exception as e:
                        logger.error(f"Error making second LLM call after tool execution: {e}", exc_info=True)
                
                if not output or output.strip() == "":
                    logger.warning(f"Specialist '{specialist_name}' returned empty output for attendance {attendance_id}")
                
                def _build_usage(out_len: int = 0) -> dict:
                    pt = usage_cb.prompt_tokens
                    ct = usage_cb.completion_tokens
                    tt = usage_cb.total_tokens
                    if tt <= 0 and (openai_cb.prompt_tokens or openai_cb.completion_tokens or openai_cb.total_tokens):
                        pt = openai_cb.prompt_tokens
                        ct = openai_cb.completion_tokens
                        tt = openai_cb.total_tokens or (pt + ct)
                    if tt <= 0:
                        est_pt = max(0, (len(system_message) + len(message_content)) // 4)
                        est_ct = max(0, out_len // 4)
                        pt = est_pt
                        ct = est_ct
                        tt = pt + ct
                        if tt > 0:
                            logger.info("Token usage not captured; using estimated tokens", extra={"prompt": pt, "completion": ct, "total": tt})
                    return {"prompt_tokens": pt, "completion_tokens": ct, "total_tokens": tt}
                
                try:
                    import re
                    logger.info(f"Processing specialist '{specialist_name}' output for attendance {attendance_id}")
                    
                    pre_fragmented = result.get("_pre_fragmented")
                    if pre_fragmented is not None:
                        final_output, fragments = pre_fragmented
                        result.pop("_pre_fragmented", None)
                        if not fragments:
                            fragments = [final_output]
                        logger.info(f"📝 Specialist '{specialist_name}' - RESPOSTA COMPLETA (pre-fragmented, primeiros 500 chars): {final_output[:500]}")
                        _usage = _build_usage(len(final_output))
                        fragments_metadata = {"fragments": fragments, "fragment_count": len(fragments), "from_structured_output": True}
                        logger.info(f"✅ Specialist '{specialist_name}': Using pre-fragmented output: {len(fragments)} fragments")
                        logger.info(f"📦 Specialist '{specialist_name}' - FRAGMENTOS PRE-FRAGMENTADOS: {fragments}")
                        exec_log = await self._build_execution_log(
                            _log_ctx, _log_ctx.get("messages_sent"), result.get("intermediate_steps", [])
                        )
                        return {
                            "output": final_output,
                            "intermediate_steps": result.get("intermediate_steps", []),
                            "fragments": fragments,
                            "metadata": fragments_metadata,
                            "usage": _usage,
                            "execution_log": exec_log,
                        }
                    
                    # Regex fragmentation
                    logger.info(f"📝 Specialist '{specialist_name}' - RESPOSTA COMPLETA ANTES DA FRAGMENTAÇÃO (primeiros 500 chars): {output[:500]}")
                    # Split AFTER sentence-ending punctuation only (not after decimal dots like 1.0, 100.00)
                    simple_fragments = [f.strip() for f in re.split(r'(?<=[!?]|[^\d.]\.)\s*', output) if f.strip()]
                    if not simple_fragments:
                        simple_fragments = [output]
                    final_output = output
                    fragments = simple_fragments
                    logger.info(f"✅ Specialist '{specialist_name}': Regex fragmentation: {len(fragments)} fragments")
                    logger.info(f"📦 Specialist '{specialist_name}' - FRAGMENTOS GERADOS: {fragments}")
                    
                    if not fragments:
                        fragments = [final_output]
                    _usage = _build_usage(len(final_output))
                    fragments_metadata = {"fragments": fragments, "fragment_count": len(fragments), "from_structured_output": False}
                    exec_log = await self._build_execution_log(
                        _log_ctx, _log_ctx.get("messages_sent"), result.get("intermediate_steps", [])
                    )
                    return {
                        "output": final_output,
                        "intermediate_steps": result.get("intermediate_steps", []),
                        "fragments": fragments,
                        "metadata": fragments_metadata,
                        "usage": _usage,
                        "execution_log": exec_log,
                    }
                except Exception as structured_error:
                    logger.error(f"❌ Error processing specialist '{specialist_name}' output: {structured_error}", exc_info=True)
                    import re
                    # Split AFTER sentence-ending punctuation only (not after decimal dots like 1.0)
                    simple_fragments = [f.strip() for f in re.split(r'(?<=[!?]|[^\d.]\.)\s*', output) if f.strip()]
                    if not simple_fragments:
                        simple_fragments = [output]
                    _usage = _build_usage(len(output))
                    exec_log = await self._build_execution_log(
                        _log_ctx, _log_ctx.get("messages_sent"), result.get("intermediate_steps", [])
                    )
                    return {
                        "output": output,
                        "intermediate_steps": result.get("intermediate_steps", []),
                        "fragments": simple_fragments,
                        "metadata": {"fallback": True, "fragment_count": len(simple_fragments)},
                        "usage": _usage,
                        "execution_log": exec_log,
                    }
        except Exception as e:
            logger.error(f"Error processing message with specialist '{self.specialist_config.get('name', 'Unknown')}': {e}", exc_info=True)
            return {
                "output": "",
                "intermediate_steps": [],
                "fragments": [],
                "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
                "execution_log": await self._build_execution_log({}, None, []),
            }
    
    async def _process_function_calls(
        self,
        intermediate_steps: List,
        attendance_id: str,
        client_phone: str,
        agent_result: Dict
    ) -> Optional[str]:
        """
        Process function calls executed by the specialist agent
        
        Returns:
            Last processed_output when has_output and is_sync; None otherwise
        """
        last_processed_output: Optional[str] = None
        try:
            from utils.postgres_client import pg_client
            
            if not pg_client.pool:
                logger.warning("PostgreSQL client not connected, skipping function call processing")
                return None
            
            try:
                for step in intermediate_steps:
                    if not step or len(step) < 2:
                        continue
                    
                    action = step[0]
                    tool_result = step[1]
                    
                    tool_name = None
                    if hasattr(action, 'tool'):
                        tool_name = action.tool
                    elif isinstance(action, dict) and 'tool' in action:
                        tool_name = action['tool']
                    
                    if not tool_name:
                        continue
                    
                    # Get function call config from agent_function_calls (new table)
                    config_row = await pg_client.fetchrow(
                        """
                        SELECT has_output, processing_method
                        FROM agent_function_calls
                        WHERE name = $1 AND is_active = true
                        """,
                        tool_name
                    )
                    
                    if not config_row:
                        logger.warning(f"Function call config not found for {tool_name}")
                        continue
                    
                    has_output = config_row.get('has_output', False)
                    is_sync = True  # agent_function_calls has no is_sync; default sync
                    processing_method = (config_row.get('processing_method') or 'RABBITMQ').upper()
                    
                    if processing_method == 'RABBITMQ' and self.function_call_processor:
                        result = await self.function_call_processor.process_function_call(
                            function_call_name=tool_name,
                            result=tool_result,
                            attendance_id=attendance_id,
                            client_phone=client_phone,
                            has_output=has_output,
                            is_sync=is_sync
                        )
                        
                        if has_output and is_sync and result and result.get('output'):
                            last_processed_output = result['output']
                    
            except Exception as e:
                logger.error(f"Error processing function calls: {e}", exc_info=True)
            
            return last_processed_output
        except Exception as e:
            logger.error(f"Error in _process_function_calls: {e}", exc_info=True)
            return None
